### ISSUE TITLE
Install fails with no matching function call

### ISSUE THREAD

**Issue by Nomenator** [laverdet/isolated-vm#134]
```
:~$ npm install isolated-vm

> isolated-vm@2.0.1 install /home/user/node_modules/isolated-vm
> node-gyp rebuild --release -j 4

make: Entering directory '/home/user/node_modules/isolated-vm/build'
  CXX(target) Release/obj.target/nortti/src/external_copy_nortti.o
In file included from ../src/external_copy.h:10:0,
                 from ../src/external_copy_nortti.cc:1:
../src/isolate/util.h: In function ‘bool ivm::IsOptionSet(const v8::Local<v8::Context>&, const v8::Local<v8::Object>&, const char*)’:
../src/isolate/util.h:28:82: error: no matching function for call to ‘v8::Value::ToBoolean(const v8::Local<v8::Context>&)’
  return Unmaybe(Unmaybe(options->Get(context, v8_string(key)))->ToBoolean(context))->IsTrue();
                                                                                  ^
In file included from ../src/external_copy.h:2:0,
                 from ../src/external_copy_nortti.cc:1:
/home/user/.cache/node-gyp/13.0.1/include/node/v8.h:2631:18: note: candidate: v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const
   Local<Boolean> ToBoolean(Isolate* isolate) const;
                  ^~~~~~~~~
/home/user/.cache/node-gyp/13.0.1/include/node/v8.h:2631:18: note:   no known conversion for argument 1 from ‘const v8::Local<v8::Context>’ to ‘v8::Isolate*’
nortti.target.mk:110: recipe for target 'Release/obj.target/nortti/src/external_copy_nortti.o' failed
make: *** [Release/obj.target/nortti/src/external_copy_nortti.o] Error 1
make: Leaving directory '/home/user/node_modules/isolated-vm/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-17763-Microsoft
gyp ERR! command "/home/user/.nvm/versions/node/v13.0.1/bin/node" "/home/user/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /home/user/node_modules/isolated-vm
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
npm WARN user No description
npm WARN user No repository field.
npm WARN user No README data
npm WARN user No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@2.0.1 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-11-02T04_32_07_258Z-debug.log
```

Really don't know what to make of this. Language version mismatch? Missed prerequisite?

**Comment by laverdet** [comment]
Try nodejs v12.x

**Comment by Nomenator** [comment]
@laverdet thanks, that worked out very well with v 12.13.0
