### ISSUE TITLE
Script run (async) does not reject the promise on error

### ISSUE THREAD

**Issue by rs** [laverdet/isolated-vm#15]
The `timeout` on `Script.run` seems to interrupt the execution but does not reject the returned promise.

Same with exceptions thrown in unchained promises:

```js
const ivm = require("isolated-vm");

function runSync() {
	const isolate = new ivm.Isolate();
	const context = isolate.createContextSync();
	const script = isolate.compileScriptSync('new Promise(() => {throw new Error("some error")})');

	try {
		script.runSync(context);
		console.log('sync not caught');
	} catch (e) {
		console.log('sync caught', e);
	}
}



async function runAsync() {
	const isolate = new ivm.Isolate();
	const context = await isolate.createContext();
	const script = await isolate.compileScript('new Promise(() => {throw new Error("some error")})');

	try {
		await script.run(context);
		console.log('async not caught');
	} catch (e) {
		console.log('async caught', e);
	}
}

runSync();
runAsync();
```

Output:
```
sync caught Error: some error
    at runSync (…:9:10)
    at Object.<anonymous> (…:31:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
async not caught
```

**Comment by rs** [comment]
The provided code does still fail for me.
