### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by tobowers** [laverdet/isolated-vm#178]
Hi hi. I tried doing an `npm i isolated-vm` on my osx box. I have node-gyp v6.1.0 and node v12.1.0 installed

```
$ npm install isolated-vm

> isolated-vm@3.3.1 install /Users/tobowers/code/explore-graphql/node_modules/isolated-vm
> node-gyp rebuild --release -j 4

  CXX(target) Release/obj.target/nortti/src/external_copy/serializer_nortti.o
In file included from ../src/external_copy/serializer_nortti.cc:1:
../src/external_copy/serializer.h:10:27: error: unknown type name 'WasmCompiledModule'
        using WasmModuleObject = WasmCompiledModule;
                                 ^
1 error generated.
make: *** [Release/obj.target/nortti/src/external_copy/serializer_nortti.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /Users/tobowers/code/explore-graphql/node_modules/isolated-vm
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

**Comment by laverdet** [comment]
Thanks, I've fixed this on github and will push to npm some time later. You can try now directly from github via: `npm install git@github.com:laverdet/isolated-vm.git` or (recommended) you can update nodejs to the latest v12.x release where it already works.

**Comment by laverdet** [comment]
Commit ref: ad54740d157ef536896390d6686068706583398d

**Comment by tobowers** [comment]
Thank you - I upgraded to node 13 and it all just worked.
