### ISSUE TITLE
Cannot install(build) a package

### ISSUE THREAD

**Issue by mecurc** [laverdet/isolated-vm#200]
**Versions**
MacOS: 10.15.6
nodejs: v14.8.0
Clang: 12.0.0 (clang-1200.0.31.1)
CommandLineTools: 12.0.0.0.1.1597368733

**install log (when i run `npm i isolated-vm`)**
```
❯ npm i isolated-vm

> isolated-vm@3.3.5 install /Users/dv/Documents/startup-types/node_modules/isolated-vm
> node-gyp rebuild --release -j 4

  CXX(target) Release/obj.target/nortti/src/external_copy/serializer_nortti.o
  CXX(target) Release/obj.target/nortti/src/isolate/allocator_nortti.o
In file included from In file included from ../src/isolate/allocator_nortti.cc:../src/external_copy/serializer_nortti.cc2::
1In file included from :
../src/isolate/environment.hIn file included from :../src/external_copy/serializer.h5::
2In file included from :
../src/isolate/executor.hIn file included from :../src/external_copy/external_copy.h6::
12In file included from :
../src/isolate/holder.hIn file included from :../src/isolate/util.h2::
36In file included from :
../src/isolate/platform_delegate.hIn file included from :../src/isolate/remote_handle.h2::
3:
In file included from ../src/isolate/environment.h:../src/lib/lockable.h5::
93In file included from :../src/isolate/executor.h21::6 :
In file included from ../src/isolate/holder.herror:: 2:
In file included from ../src/isolate/platform_delegate.h:2'shared_timed_mutex':
 is unavailable:../src/lib/lockable.h :introduced93 :in21 :macOS  10.12error
: 'shared_timed_mutex' is unavailable: introduced in macOS 10.12
        using Mutex = std::shared_timed_mutex;
                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/shared_mutex:205:        using Mutex = std::shared_timed_mutex;58
:                            ^
note: 'shared_timed_mutex' has been/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/shared_mutex :explicitly205 :marked58
:       unavailable herenote: 
'shared_timed_mutex' has been explicitly marked
      unavailable here
class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_timed_mutex
                                                         ^
class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_timed_mutex
                                                         ^
1 error generated.
make: *** [Release/obj.target/nortti/src/isolate/allocator_nortti.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [Release/obj.target/nortti/src/external_copy/serializer_nortti.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dv/.n/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/dv/.n/bin/node" "/Users/dv/.n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /Users/dv/Documents/startup-types/node_modules/isolated-vm
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN startup-types@1.0.0 No description
npm WARN startup-types@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@3.3.5 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isolated-vm@3.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dv/.npm/_logs/2020-08-25T18_22_01_348Z-debug.log
```

**Debug log (/Users/dv/.npm/_logs/2020-08-25T18_22_01_348Z-debug.log)**
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dv/.n/bin/node', '/Users/dv/.n/bin/npm', 'i', 'isolated-vm' ]
2 info using npm@6.14.7
3 info using node@v14.8.0
4 verbose npm-session bbca65c69797054f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/isolated-vm 2005ms
8 http fetch GET 200 https://registry.npmjs.org/isolated-vm/-/isolated-vm-3.3.5.tgz 193ms
9 silly pacote tag manifest for isolated-vm@latest fetched in 2212ms
10 timing stage:loadCurrentTree Completed in 2283ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule isolated-vm@3.3.5 checking installable status
18 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 5ms
19 timing stage:loadIdealTree Completed in 8ms
20 silly currentTree startup-types@1.0.0
20 silly currentTree ├── rxjs@6.6.2
20 silly currentTree ├── tslib@1.13.0
20 silly currentTree └── typescript@4.0.2
21 silly idealTree startup-types@1.0.0
21 silly idealTree ├── isolated-vm@3.3.5
21 silly idealTree ├── rxjs@6.6.2
21 silly idealTree ├── tslib@1.13.0
21 silly idealTree └── typescript@4.0.2
22 silly install generateActionsToTake
23 timing stage:generateActionsToTake Completed in 7ms
24 silly diffTrees action count 1
25 silly diffTrees add isolated-vm@3.3.5
26 silly decomposeActions action count 8
27 silly decomposeActions fetch isolated-vm@3.3.5
28 silly decomposeActions extract isolated-vm@3.3.5
29 silly decomposeActions preinstall isolated-vm@3.3.5
30 silly decomposeActions build isolated-vm@3.3.5
31 silly decomposeActions install isolated-vm@3.3.5
32 silly decomposeActions postinstall isolated-vm@3.3.5
33 silly decomposeActions finalize isolated-vm@3.3.5
34 silly decomposeActions refresh-package-json isolated-vm@3.3.5
35 silly install executeActions
36 silly doSerial global-install 8
37 verbose correctMkdir /Users/dv/.npm/_locks correctMkdir not in flight; initializing
38 verbose lock using /Users/dv/.npm/_locks/staging-410e472e9104d6dc.lock for /Users/dv/Documents/startup-types/node_modules/.staging
39 silly doParallel extract 1
40 silly extract isolated-vm@3.3.5
41 silly tarball trying isolated-vm@latest by hash: sha512-1YGaryLTjd68WvvfQL/wZD9JzuXM8PbTSwcwFYTMcY+fIUmU3Iem4RZhH/21IDC7TW7wrviMfPq+EHtFOYMGAw==
42 silly extract isolated-vm@latest extracted to /Users/dv/Documents/startup-types/node_modules/.staging/isolated-vm-aa41bae3 (44ms)
43 timing action:extract Completed in 46ms
44 silly doReverseSerial unbuild 8
45 silly doSerial remove 8
46 silly doSerial move 8
47 silly doSerial finalize 8
48 silly finalize /Users/dv/Documents/startup-types/node_modules/isolated-vm
49 timing action:finalize Completed in 3ms
50 silly doParallel refresh-package-json 1
51 silly refresh-package-json /Users/dv/Documents/startup-types/node_modules/isolated-vm
52 timing action:refresh-package-json Completed in 5ms
53 silly doParallel preinstall 1
54 silly preinstall isolated-vm@3.3.5
55 info lifecycle isolated-vm@3.3.5~preinstall: isolated-vm@3.3.5
56 timing action:preinstall Completed in 1ms
57 silly doSerial build 8
58 silly build isolated-vm@3.3.5
59 info linkStuff isolated-vm@3.3.5
60 silly linkStuff isolated-vm@3.3.5 has /Users/dv/Documents/startup-types/node_modules as its parent node_modules
61 timing action:build Completed in 1ms
62 silly doSerial global-link 8
63 silly doParallel update-linked 0
64 silly doSerial install 8
65 silly install isolated-vm@3.3.5
66 info lifecycle isolated-vm@3.3.5~install: isolated-vm@3.3.5
67 verbose lifecycle isolated-vm@3.3.5~install: unsafe-perm in lifecycle true
68 verbose lifecycle isolated-vm@3.3.5~install: PATH: /Users/dv/.n/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dv/Documents/startup-types/node_modules/isolated-vm/node_modules/.bin:/Users/dv/Documents/startup-types/node_modules/.bin:/Users/dv/.venv/bin:/Users/dv/.n/bin:/usr/local/opt/openjdk/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dv/.venv/bin:/Users/dv/.n/bin:/usr/local/opt/openjdk/bin
69 verbose lifecycle isolated-vm@3.3.5~install: CWD: /Users/dv/Documents/startup-types/node_modules/isolated-vm
70 silly lifecycle isolated-vm@3.3.5~install: Args: [ '-c', 'node-gyp rebuild --release -j 4' ]
71 timing audit submit Completed in 996ms
72 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 996ms
73 timing audit body Completed in 0ms
74 silly lifecycle isolated-vm@3.3.5~install: Returned: code: 1  signal: null
75 info lifecycle isolated-vm@3.3.5~install: Failed to exec install script
76 timing action:install Completed in 1793ms
77 verbose unlock done using /Users/dv/.npm/_locks/staging-410e472e9104d6dc.lock for /Users/dv/Documents/startup-types/node_modules/.staging
78 timing stage:rollbackFailedOptional Completed in 24ms
79 timing stage:runTopLevelLifecycles Completed in 4188ms
80 silly saveTree startup-types@1.0.0
80 silly saveTree ├── isolated-vm@3.3.5
80 silly saveTree ├─┬ rxjs@6.6.2
80 silly saveTree │ └── tslib@1.13.0
80 silly saveTree └── typescript@4.0.2
81 warn startup-types@1.0.0 No description
82 warn startup-types@1.0.0 No repository field.
83 verbose stack Error: isolated-vm@3.3.5 install: `node-gyp rebuild --release -j 4`
83 verbose stack Exit status 1
83 verbose stack     at EventEmitter.<anonymous> (/Users/dv/.n/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
83 verbose stack     at EventEmitter.emit (events.js:314:20)
83 verbose stack     at ChildProcess.<anonymous> (/Users/dv/.n/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
83 verbose stack     at ChildProcess.emit (events.js:314:20)
83 verbose stack     at maybeClose (internal/child_process.js:1051:16)
83 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
84 verbose pkgid isolated-vm@3.3.5
85 verbose cwd /Users/dv/Documents/startup-types
86 verbose Darwin 19.6.0
87 verbose argv "/Users/dv/.n/bin/node" "/Users/dv/.n/bin/npm" "i" "isolated-vm"
88 verbose node v14.8.0
89 verbose npm  v6.14.7
90 error code ELIFECYCLE
91 error errno 1
92 error isolated-vm@3.3.5 install: `node-gyp rebuild --release -j 4`
92 error Exit status 1
93 error Failed at the isolated-vm@3.3.5 install script.
93 error This is probably not a problem with npm. There is likely additional logging output above.
94 verbose exit [ 1, true ]
```

**Comment by laverdet** [comment]
Are you using a beta version of Apple's developer tools?

**Comment by mecurc** [comment]
Hello!
Hi!

Yes, I use the beta version. But I did some manipulations and I was able to install the package:
```sh
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

Now the package is successfully installed

But after that MacOS offers me an upgrade:
```
Software Update Tool

Finding available software
Software Update found the following new or updated software:
* Label: Command Line Tools beta 5 for Xcode-12.0
	Title: Command Line Tools beta 5 for Xcode, Version: 12.0, Size: 442912K, Recommended: YES,
```

After installing the update, I cannot install the package again.

**Comment by laverdet** [comment]
I've submitted a bug report to Apple about this. In the mean time please use a non-beta Xcode to compile this project.

I'll probably have to include a workaround for the issue in a future release because I'm not sure how quick Apple is to respond about bug reports.

**Comment by mecurc** [comment]
Awesome!

Thank you for your work.

**Comment by spy4x** [comment]
Hello @laverdet 
Thank you for your library!
I have same issue as mecurc, but I don't use beta CommandLineTools.
My macOS is Big Sur v11.0.1.
I tried to reinstall CommandLineTools from scratch, but it didn't help.
I tried Node.js v10 and v12.

Do you have any workarounds in mind that could help?
Trying to launch Screeps server locally :)

**Comment by Dids** [comment]
Same issue on macOS Catalina 10.15.7 with the latest public/stable version of Xcode (12.3). Seems like this change is permanent.
