### ISSUE TITLE
Timeout is ignored when creating very large `BigInt`s

### ISSUE THREAD

**Issue by y21** [laverdet/isolated-vm#202]
If a timeout is provided and supplied code ends in an infinite loop or similar so that it exceeds this limit, an error saying 'Script execution timed out' is thrown. However, when the BigInt constructor is called with a very large number (>= 1e8) as parameter, this "task" never gets killed. Instead, it tries to construct this BigInt and (maybe similar to `Array.prototype.fill` in an earlier version of v8?) the isolate becomes unresponsive (`Isolate#getHeapStatistics` and other methods hang) until it's done.

Reproducible code
```js
const ivm = require('isolated-vm');

(async () => {
    const isolate = new ivm.Isolate();
    const ctx = await isolate.createContext();

    await ctx.eval('BigInt("1".repeat(1e8))', {
        timeout: 100
    }).then(x => x.result);
})();
```

Node.js: v14.7.0
v8: 8.4.371.19-node.12
ivm: 3.3.5

**Comment by laverdet** [comment]
The bad news is that this error can't be fixed with a polyfill like the Array.fill issue. Even with a polyfill you could end up with `ctx.eval('eval("1".repeat(1e8) + "n")')` which invokes the same problematic v8 code but directly from the parser.

The good news is that the fix in v8 seems relatively simple. I hacked this together which fixes the issue on my end:
```diff
diff --git a/src/numbers/conversions.cc b/src/numbers/conversions.cc
index 70d914e6df..790a836aa8 100644
--- a/src/numbers/conversions.cc
+++ b/src/numbers/conversions.cc
@@ -246,6 +246,7 @@ class StringToIntHelper {
   void set_state(State state) { state_ = state; }
 
  private:
+  bool CheckTermination();
   template <class Char>
   void DetectRadixInternal(Char current, int length);
   template <class Char>
@@ -295,6 +296,16 @@ void StringToIntHelper<LocalIsolate>::ParseInt() {
   DCHECK_NE(state_, State::kRunning);
 }
 
+template <typename LocalIsolate>
+bool StringToIntHelper<LocalIsolate>::CheckTermination() { return false; }
+
+template <>
+bool StringToIntHelper<Isolate>::CheckTermination() {
+  StackLimitCheck interrupt_check(isolate());
+  return interrupt_check.InterruptRequested() &&
+    isolate()->stack_guard()->HandleInterrupts().IsException(isolate());
+}
+
 template <typename LocalIsolate>
 template <class Char>
 void StringToIntHelper<LocalIsolate>::DetectRadixInternal(Char current,
@@ -425,7 +436,7 @@ void StringToIntHelper<LocalIsolate>::ParseInternal(Char start) {
       DCHECK(multiplier > part);
 
       ++current;
-      if (current == end) {
+      if (current == end || CheckTermination()) {
         done = true;
         break;
       }
```

The pipeline from v8 pull request to nodejs release is a slow one so if this issue is causing you problems you'll have to patch nodejs and compile yourself. I'll post here with updates when I reach out to the v8 team about the issue.

**Comment by laverdet** [comment]
My fix landed in v8 today -- https://chromium-review.googlesource.com/c/v8/v8/+/2384166

I can probably convince the nodejs team to cherrypick this into nodejs v14.x. I found out that this materially affects vanilla nodejs. If you copy and paste `BigInt("1".repeat(1e8))` into the nodejs REPL it locks up the process before you even press enter.

**Comment by y21** [comment]
Also, the `Function` constructor seems to be uninterruptible as well.

```js
const { Isolate } = require('isolated-vm');
const isolate = new Isolate({
    memoryLimit: 8
});

(async () => {
    const ctx = await isolate.createContext();

    try {
        await ctx.eval(`Function('1'.repeat(40).repeat(1e7));`, {
            timeout: 100
        });
    } catch(e) {
        console.error(e.message);
    } finally {
        console.log('CPU Time', isolate.cpuTime);
    }
})();
```

![image](https://user-images.githubusercontent.com/30553356/94204078-da6d6600-fec0-11ea-8a29-6fe8e7aac9b9.png)

**Comment by laverdet** [comment]
You can definitely report them here first. v8's parser is uninterruptible and that will probably never change. In this case, v8 gives you a hook to validate any source passed to the "eval family" of functions. So we can just throw out any unreasonably long strings and refuse to compile them.

**Comment by y21** [comment]
Oh interesting. I knew the `Function` one would be different than those BigInt and Array.fill issues and it makes sense that the parser is uninterruptible, but I didn't know v8 lets embedded applications reject compilation like that. Thanks for clarifying!

**Comment by y21** [comment]
Also,  `'1'.repeat(53).repeat(1e7).split('');` OOM's the node process (node v14.7.0, v8 8.4.371.19-node.12)

**Comment by y21** [comment]
Another one that locks up the isolate for a long time and allocates a lot of memory, though I'm not sure if it's fixed by the recent commit: `eval('~'.repeat(1e4) + '1'.repeat(52).repeat(1e7));`

Tried messing around a bit more and found out the following code kills IVM. Couldn't reproduce it on my local machine though, so not sure if this is an actual bug or just something wrong with my environment
```js
const { Isolate } = require('isolated-vm');
const isolate = new Isolate({ memoryLimit: 8 });

(async () => {
    const ctx = await isolate.createContext();

    const s = '~'.repeat(1e6);

    await ctx.eval(s);
})();
```
![image](https://user-images.githubusercontent.com/30553356/94377735-23712480-0124-11eb-884d-6c3c7158c038.png)

**Comment by laverdet** [comment]
The `split` case is tough. v8 has a maximum array length of 0x7ffffff. If you try to allocate an array larger than this it just blows up immediately, no escape hatch or anything. The size limit for strings is at least 4 times larger than this, and there's lots of ways of to turn strings into arrays.

All of these crash the process in various ways:
```js
ctx.evalSync("'1'.repeat(0x7ffffff).split('');");
ctx.evalSync("'1'.repeat(0x7ffffff).split(/./)");
ctx.evalSync("'1'.repeat(0x7ffffff).split(/1/)");
ctx.evalSync("[].join.call('1'.repeat(0x7ffffff))");
ctx.evalSync("[].slice.call('1'.repeat(0x7ffffff))");
ctx.evalSync("[].sort.call('1'.repeat(0x7ffffff))");
ctx.evalSync("JSON.parse('[' + '1,'.repeat(0x7fffffd) + '1]')");
```

There's no doubt lots of other examples. They can probably mostly be cleaned up with runtime patches. I still don't have a way to automatically do this, but the fix for theses cases could eventually be wound up with #107.

**Comment by y21** [comment]
Another one that crashes ivm:
```js
const {Isolate} = require('isolated-vm');

const isolate = new Isolate({memoryLimit: 128});

const ctx = isolate.createContextSync();

ctx.eval('/1+2/.test("1".repeat(1024 ** 2 * 127));', {
    timeout: 100
});
```

```sh
$ node test6.js
node: ../src/isolate/run_with_timeout.h:136: ivm::RunWithTimeout(uint32_t, F&&)::<lambda(void*)> [with F = ivm::EvalRunner::Phase2()::<lambda()>]: Assertion `false' failed.
Aborted (core dumped)
```

**Comment by y21** [comment]
Here's one that causes node to segfault:
```js
const {Isolate} = require('isolated-vm');

const isolate = new Isolate({memoryLimit: 128});

const ctx = isolate.createContextSync();

ctx.eval(`
    const a = []; for (let i = 0; i < 512; ++i) a.push(0);
    Math.max(...a.map(() => '1'.repeat(1024 ** 2 * 127)));
`);



setTimeout(() => {
    isolate.dispose();
    isolate.cpuTime;
}, 1000);
```

```sh
/home/y21/test/test3.js:16
    isolate.cpuTime;
            ^

Error: Isolate is disposed
    at Timeout._onTimeout (/home/y21/test/test3.js:16:13)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
Segmentation fault (core dumped)
```

**Comment by pkit** [comment]
> My fix landed in v8 today -- https://chromium-review.googlesource.com/c/v8/v8/+/2384166

Reverted, it seems.

**Comment by laverdet** [comment]
I resubmitted the patch after the revert and it was accepted with some broader changes:
https://github.com/v8/v8/commit/7e8e76e784061277e13112c67c21c3f9438da257
https://chromium-review.googlesource.com/c/v8/v8/+/2392629

**Comment by pkit** [comment]
@laverdet are you ok if I backport the patch to v8 7.x ? Integrating 8.x is tricky in some places. :)

**Comment by laverdet** [comment]
@pkit sorry I'm not sure what you're asking? Do you mean you want to open a PR on nodejs?

**Comment by pkit** [comment]
@laverdet nope, a PR on plv8 which uses 7.x releases for now

**Comment by laverdet** [comment]
I don't mind, the code is part of v8 now. It sounds like that's between you and the plv8 team if this is an issue for you on that platform.

**Comment by pkit** [comment]
It seems like there's still something strange going on.
Example code: https://gist.github.com/pkit/427d3ac691882782c61e6ceec490348c
Running it like:
```
$ ./test1 'for(;;){}'
timeout = 0.500s
timed out
elapsed: 0.500s
```
```
$ ./test1 'BigInt("1".repeat(1e8))'
timeout = 0.500s
timed out
elapsed: 10.010s
```

**Comment by laverdet** [comment]
It would never terminate before my patch, now it terminates eventually 🤷🏼‍♂️

**Comment by pkit** [comment]
@laverdet yup, tested that too, will never terminate without a patch.
But cannot find where the 10 sec stuff comes from.

**Comment by pkit** [comment]
@laverdet reducing chunk size to 256 (or even 128) and breaking the multiplier loop doesn't slow down the conversion from my benchmarks. But allows for ~ 100ms timer resolution.

**Comment by laverdet** [comment]
Are you running into this super often? I do regret not picking a smaller chunk size but I'm not sure it's worth bringing the Chromium team into this again to tweak this constant. I've definitely run into other areas of the v8 codebase where interrupts can take seconds to fire, so this isn't a problem unique to this constructor.

**Comment by pkit** [comment]
Nope, not at all, I just wanted to fix at least the known uninterruptable stuff.
For now I can just recompile custom v8 when needed.

**Comment by y21** [comment]
Just to add one to the list, `encodeURI`/`encodeURIComponent` also seems to be one of those functions that are uninterruptible: it took ~100 seconds for it to terminate a task using `encodeURI('€'.repeat(0x1fffffe8))`

**Comment by y21** [comment]
Also, following code OOM crashes the process:
```js
const {Isolate} = require('isolated-vm');

const isolate = new Isolate({ memoryLimit: 32 });
const ctx = isolate.createContextSync();

ctx.eval(`
    const c = 0x1fffffe8 / 16;

    const s = () => '1'.repeat(c);

    s() ** s() ** s() ** s() ** s()
`);
```

I did read about different types of internal V8 strings/string representations (cons strings, flat strings) and how they could potentially cause OOMs, but I'm not sure if that's related

**Comment by pkit** [comment]
Hmm, most of these lead to OOM handler invocation which will either call `abort()` or return to V8 which will call `abort()` anyway.
In `plv8` I have a stack manipulation strategy where I can never return back from OOM handler, and can dispose of the isolate safely later. Essentially it jumps over the `isolate->SignalFatalError()` and friends in the V8 code (may have some resource leaks, but seems fine).
Which probably means that it (unconditional `abort()`) can be safely patched out of existence for "smarter" isolate mangers like `isolated-vm`?

**Comment by laverdet** [comment]
I assume you're talking about setjmp & longjmp? Jumping over a non-trivial destructor is UB. I'm actually planning on locking the thread when the OOM handler and invoking some callback in js. That would give the developer a chance to gracefully restart the process and log the error.

**Comment by pkit** [comment]
Yup, `setsigjump` and friends. I don't see anything non-trivial in the v8 code there though.
And they do allocate things on stack for all the contexts.
I can kill the process, but that's kind of wasteful, one isolate kills all of them. When memory of only one is exhausted.

**Comment by laverdet** [comment]
Just grep the v8 codebase for "~" or "std". There's are *lots* of non-trivial destructors and you *are* relying on UB. This is definitely an architectural problem in v8 but the fix is certainly not to `on error resume next`. You really do need to kill the whole process away in this case.

**Comment by pkit** [comment]
Hmm, let's consider the following code:
```
void SomeFunction(Isolate *isolate)
{
  Isolate::Scope scope(isolate);
  HandleScope handle_scope(isolate);
  Local<Context> context = GetSomeContext();
  Context::Scope context_scope(context);
  ....
  isolate->Exit();
  isolate->Destroy();
}
```
What would happen with all these non-trivial destructors (ex. `~HandleScope()`), what will they do?
What I see is something like `if (isolate_ == nullptr) return;` in the relevant places in v8 code, because I have no idea how else it can work when you can actually call `Exit()` and/or `Destroy()` from anywhere.
Maybe I'm missing something?

**Comment by laverdet** [comment]
You're not just throwing away the topmost frame, you're also throwing away all the frames under it. Log a backtrace and you'll see that v8 has dozens of frames that you are jumping out of, who knows what cleanup they'll want to do. You're violating a pretty important invariant in this application. You may end up deallocating a locked mutex or corrupting v8's platform metadata. Maybe under some conditions it works but other conditions it will delete you hard drive. Maybe it works under all conditions now but it will break catastrophically in the future. The behavior is *undefined*.

From a technical perspective it doesn't matter *what* the destructor does, skipping it results in undefined behavior: https://en.cppreference.com/w/cpp/utility/program/longjmp
>  No destructors for automatic objects are called. If replacing of std::longjmp with throw and setjmp with catch would execute a non-trivial destructor for any automatic object, the behavior of such std::longjmp is undefined.

I've been writing dangerous "dragons ahead" hacky stuff all my life and this is not something even I would bother with.

**Comment by pkit** [comment]
I totally agree with your assessment.
It's C++, any time you step into UB all bets are off...
But have no choice right now.
I'm cleaning up the process, but not immediately.

**Comment by Gongreg** [comment]
Hello, I wanted to get some clarification on this issue.

Lets take the following code snippet:

```javascript
const { Isolate } = require("isolated-vm")

let isolate = new Isolate({ memoryLimit: 128 })
let ctx = isolate.createContextSync()

setInterval(async () => {
  ctx.release()
  isolate.dispose()

  isolate = new Isolate({ memoryLimit: 128 })
  ctx = isolate.createContextSync()

  ctx.eval('BigInt("1".repeat(1e8))', {
    timeout: 100,
  })

  console.log(process.memoryUsage())
}, 1000)
```


As far as I understand it is expected that doing the isolates will go over defined memory limit (saw that mentioned in multiple issues).

But what I am not able to find info about, is it is expected that trying to `dispose` of the isolate is going to fail & the memory usage is going to keep increasing?

```
{
  rss: 103579648,
  heapTotal: 40501248,
  heapUsed: 34076056,
  external: 1162687,
  arrayBuffers: 41942
}
{
  rss: 357187584,
  heapTotal: 40501248,
  heapUsed: 34090424,
  external: 1162727,
  arrayBuffers: 41942
}
{
  rss: 558678016,
  heapTotal: 40501248,
  heapUsed: 34098112,
  external: 1162727,
  arrayBuffers: 41942
}
{
  rss: 743833600,
  heapTotal: 40501248,
  heapUsed: 34105560,
  external: 1162727,
  arrayBuffers: 41942
}
{
  rss: 945946624,
  heapTotal: 40501248,
  heapUsed: 34113160,
  external: 1162727,
  arrayBuffers: 41942
}
{
  rss: 1131200512,
  heapTotal: 40501248,
  heapUsed: 34120936,
  external: 1162727,
  arrayBuffers: 41942
}
{
  rss: 1323040768,
  heapTotal: 40501248,
  heapUsed: 34128552,
  external: 1162727,
  arrayBuffers: 41942
}
{
  rss: 1517076480,
  heapTotal: 40501248,
  heapUsed: 34137200,
  external: 1162727,
  arrayBuffers: 41942
}
{
  rss: 1696989184,
  heapTotal: 33947648,
  heapUsed: 31329152,
  external: 1142050,
  arrayBuffers: 24798
}
{
  rss: 1882669056,
  heapTotal: 33947648,
  heapUsed: 31415704,
  external: 1142050,
  arrayBuffers: 24798
}
{
  rss: 2080964608,
  heapTotal: 33947648,
  heapUsed: 31448464,
  external: 1142050,
  arrayBuffers: 24798
}
```


If this is expected, maybe there are recommendations how to recover from the following scenario?

**Comment by pkit** [comment]
This one I think fails in the compiler. And compiler in v8 is not interruptable.
To fix: fix it in v8.
V8 has two main security problems, IMHO.
1. Compiler is not interruptable.
2. OOM just kills everything.
I have kinda "fixed" those by doing ugly stuff above in plv8.
But it is ugly stuff and I'm lucky that it worked.

**Comment by laverdet** [comment]
@Gongreg that's actually surprising to hear because I personally fixed this exact issue [very large BigInt parses] in v8 back in 2020: https://github.com/v8/v8/commit/7e8e76e784061277e13112c67c21c3f9438da257. I did kind of regret not making the chunk size smaller since it would take at least 250ms to time out if I remember correctly. I wonder if it regressed.

**Comment by laverdet** [comment]
Regardless, it's clear that a very big rearchitecture needs to happen in order to harden isolated-vm. The whole thing really needs to be rebuilt on a multi-process abstraction to protect against the speculative execution attacks disclosed in 2018. This would also address the shared heap issues which popped up in nodejs v19.x as well. That's a month long project that I just don't have the spare time for though.

`onCatastrophicError` is a stop gap solution for this kind of issue though. It provides a signal that v8 has failed to terminate and isolated-vm intentionally permanently deadlocks the thread to prevent it from doing any more damage. It gives you the opportunity to gracefully shut down the server, and potentially mark this script or user as problematic to avoid running their code in the future.
