### ISSUE TITLE
Memory leak when manually error thrown within promises

### ISSUE THREAD

**Issue by kiddkai** [laverdet/isolated-vm#252]
Hi,

Thank you for such a amazing library!

We found a bug when we where stress testing the new runtime we created based on isolated-vm. We found that when a 3rd party code throw an error within a immediate promise resolve. `context.release()` will not be able to cleanup the memory used. At the end, isolate bailed out and throw an OOM.

We ran it in `Node@14` and `Node@12`, and able to reproduce it via this script:

```js
const { AsyncResource } = require('async_hooks');

const ivm = require('isolated-vm')

const snapshot = ivm.Isolate.createSnapshot([
    {
        code: `
            function run () {
                const storage = [];
	            const twoMegabytes = 1024 * 1024 * 2;
	            const array = new Uint8Array(twoMegabytes);
	            storage.push(array);
                
                Promise.resolve(true).then(() => {
                    throw new Error('async error')
                });
            };
        `
    }
]);

const isolate = new ivm.Isolate({
    snapshot,
    memoryLimit: 8
})

const main = async () => {
    for (let i = 0; i < 10000; i++) {
        const asyncResource = new AsyncResource(
          "RUNTIME", { triggerAsyncId: executionAsyncId(), requireManualDestroy: false }
        );

        console.log('start')
        await asyncResource.runInAsyncScope(async () => {
            const context = isolate.createContextSync();

            try {
                await context.evalClosure(`
                    run()
                `);
                console.log('here');
            } catch {
                console.log('error caught');
                asyncResource.emitDestroy();
            } finally {
                console.log('finally');
                context.release();
                global.gc();
            }

        });
        console.log('end')
    }
};

main();

```

The end result was that the isolate will be disposed:

```
(node:296869) UnhandledPromiseRejectionWarning: Error: Isolate was disposed during execution due to memory limit
    at /test.js:36:37
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at main (/test.js:35:29)
    at (<isolated-vm boundary>)
    at /test.js:36:37
```

**Comment by kiddkai** [comment]
Our use case currently is:

* Create a reletive big isolate with high memoryLimit (eg: 1024m) - the reason behind that we are runing giant apps that loads a log of code.
* Create a lot of small contexts to handle each request (for fast and isolation between requests).
* `.release()` the context after the request life-cycle is done.

Since the code we are running against are 3rd party code, so we can not gurrantly that they are throwing error anywhere in the code.

I am wondering if there's any way to properly clean it up? Our current work-around is to manually `dispose()` the isolate after certain amount of requests to make sure the server won't crash.

**Comment by kiddkai** [comment]
Thank you @laverdet!
