### ISSUE TITLE
Isolates occasionally hang entire node process

### ISSUE THREAD

**Issue by bensalilijames** [laverdet/isolated-vm#299]
Hey there, firstly thank you for this excellent library! 🙌 

We are experiencing an issue similar to #156, where very occasionally an isolate hangs and locks up the node process. The odd thing is that I cannot reliably reproduce this, it only happens, say, 1 in 100 times, so I imagine there is a race condition somewhere or I'm not understanding how to execute code in the isolate correctly. 😅 

The environment is an Alpine Linux image in Docker (`node:14-alpine`, currently `14.19.1`).

I first used `strace` to see what was going on, and it appears that the process forever waits for a `futex` to unlock:

```
/usr/src/app # strace -p 1
strace: Process 1 attached
futex(0x7fee5c4c8bdc, FUTEX_WAIT_PRIVATE, 2147483664, NULL
```

Looking into `gdb` output, we see:

```
(gdb) bt
#0  __syscall_cp_c (nr=202, u=140661727464412, v=128, w=-2147483632, x=0, y=0, z=0) at ./arch/x86_64/syscall_arch.h:61
#1  0x00007fee623f1d2a in __futex4_cp (to=0x0, val=-2147483632, op=128, addr=0x7fee5c4c8bdc) at src/thread/__timedwait.c:24
#2  __timedwait_cp (addr=addr@entry=0x7fee5c4c8bdc, val=val@entry=-2147483632, clk=clk@entry=0, at=at@entry=0x0, priv=priv@entry=128) at src/thread/__timedwait.c:52
#3  0x00007fee623f1dd1 in __timedwait (addr=addr@entry=0x7fee5c4c8bdc, val=-2147483632, clk=clk@entry=0, at=at@entry=0x0, priv=priv@entry=128) at src/thread/__timedwait.c:68
#4  0x00007fee623f3e6e in __pthread_mutex_timedlock (m=0x7fee5c4c8bd8, at=0x0) at src/thread/pthread_mutex_timedlock.c:85
#5  0x00007fee622bf00e in std::mutex::lock() () from /usr/lib/libstdc++.so.6
#6  0x00007febda8d848d in std::unique_lock<std::mutex>::lock (this=0x7ffc57913e88) at /usr/include/c++/10.3.1/bits/unique_lock.h:138
#7  0x00007febda8d5e0d in std::unique_lock<std::mutex>::unique_lock (this=0x7ffc57913e88, __m=...) at /usr/include/c++/10.3.1/bits/unique_lock.h:68
#8  0x00007febda9a6432 in ivm::detail::lock_holder_t<ivm::detail::lockable_impl_t<ivm::(anonymous namespace)::TransferablePromiseStateStruct, ivm::detail::lockable_traits_t<false, false> >, std::unique_lock<std::mutex> >::lock_holder_t (this=0x7ffc57913e80, lockable=...) at ../src/lib/lockable.h:77
#9  0x00007febda9a49f3 in ivm::detail::lockable_impl_t<ivm::(anonymous namespace)::TransferablePromiseStateStruct, ivm::detail::lockable_traits_t<false, false> >::write<>(void) (this=0x7fee5c4c8b70)
    at ../src/lib/lockable.h:156
#10 0x00007febda9a4e53 in ivm::(anonymous namespace)::TransferablePromise::TransferIn (this=0x7fee5c49f0a0) at ../src/module/transferable.cc:155
#11 0x00007febda92982a in ivm::EvalRunner::Phase3 (this=0x7fee5c0c34d0) at ../src/module/context_handle.cc:134
#12 0x00007febda908e64 in operator() (__closure=0x7ffc57913fa0) at ../src/isolate/three_phase_task.cc:170
#13 0x00007febda90a55e in ivm::FunctorRunners::RunCatchValue<ivm::ThreePhaseTask::Phase2Runner::Run()::Phase3Success::Run()::<lambda()>, ivm::ThreePhaseTask::Phase2Runner::Run()::Phase3Success::Run()::<lambda(v8::Local<v8::Value>)> >(struct {...}, struct {...}) (fn1=..., fn2=...) at ../src/isolate/functor_runners.h:75
#14 0x00007febda90900a in ivm::ThreePhaseTask::Phase2Runner::Phase3Success::Run (this=0x7fee5bf355c0) at ../src/isolate/three_phase_task.cc:168
#15 0x00007febda8e7660 in ivm::IsolateEnvironment::AsyncEntry (this=0x7fee5c4e7dd0) at ../src/isolate/environment.cc:280
#16 0x00007febda902b3e in operator() (__closure=0x0, async=0x7fee5bf841c0) at ../src/isolate/scheduler.cc:124
#17 0x00007febda902c17 in _FUN () at ../src/isolate/scheduler.cc:133
#18 0x00005584dfce51ee in uv__async_io (loop=0x5584e2c26780 <default_loop_struct>, w=<optimized out>, events=<optimized out>) at ../deps/uv/src/unix/async.c:163
#19 0x00005584dfcf85e4 in uv__io_poll (loop=loop@entry=0x5584e2c26780 <default_loop_struct>, timeout=<optimized out>) at ../deps/uv/src/unix/epoll.c:374
#20 0x00005584dfce5bf4 in uv_run (loop=0x5584e2c26780 <default_loop_struct>, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:389
#21 0x00005584df28d55c in node::NodeMainInstance::Run() ()
#22 0x00005584df205c35 in node::Start(int, char**) ()
#23 0x00007fee623bca03 in libc_start_main_stage2 (main=0x5584df181300 <main>, argc=2, argv=0x7ffc57917ce8) at src/env/__libc_start_main.c:94
#24 0x00005584df1828d1 in _start ()
```

I'm not too familiar with the C++ code in this repo, but would I be right in reading this as something going wrong with a promise being transferred back to the main process from the isolate? It looks as though locking a mutex whilst doing so waits forever.

I'm running the same code inside the isolate each time, which looks similar to this:

```js
// `untrustedSource` is a user-provided string, can have `awaits` in it,
// and should either return `true` or `false` to pass back to the main program.
const untrusted = `
  (async function execute() {
    ${untrustedSource}
  })()
`;

const isolateResult = await runtime.context.eval(untrusted, {
  promise: true,
  copy: true,
  timeout: 5000,
});

// `isolateResult` is a boolean
```

Is this the recommended way to execute code, or is there a safer way that might avoid this locking issue?

As mentioned, it's weird that it only happens a very small percentage of the time (we went months without seeing it!). I've verified that this happens on both `v4.3.6` and `v3.3.10` of `isolated-vm`.

Do let me know if there's any more info that would be helpful, and any pointers would be appreciated! Thank you! 👍

**Comment by pkit** [comment]
You can add try/catch to untrusted code.
I suspect that await runs amok after exception
```js
const untrusted = `
  (async function execute() {
    try {
    ${untrustedSource}
    } catch (e) {
    }
  })()
`;
```
But overall you cannot prevent these because of the [Halting problem](https://en.wikipedia.org/wiki/Halting_problem) :)
