### ISSUE TITLE
Issue with installing on AWS AMI Linux instance, Ubuntu 20.04 and Fedora 34

### ISSUE THREAD

**Issue by ppedziwiatr** [laverdet/isolated-vm#309]
Hey,

I'm trying to use `isolated-vm` library in AWS AMI Linux EC2 instance.

I've installed the gcc and gcc-c++
`sudo yum install gcc gcc-c++`

(the command from the readme - `sudo yum install gcc72 gcc72-c++` results in 
```
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                                                                        | 3.7 kB  00:00:00
No package gcc72 available.
No package gcc72-c++ available.
Error: Nothing to do
```
)

Now, while the npm is trying to build the isolated-vm, I'm getting this error:

```
[ec2-user@ip-172-31-17-231 redstone-sw-express-cache]$ yarn install
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠄ isolated-vm
error /home/ec2-user/redstone-sw-express-cache/node_modules/isolated-vm: Command failed.
Exit code: 1
Command: node-gyp rebuild --release -j 4
Arguments:
Directory: /home/ec2-user/redstone-sw-express-cache/node_modules/isolated-vm
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@17.3.1 | linux | x64
gyp info find Python using Python version 3.7.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/redstone-sw-express-cache/node_modules/isolated-vm/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/.cache/node-gyp/17.3.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.cache/node-gyp/17.3.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/ec2-user/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ec2-user/.cache/node-gyp/17.3.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/redstone-sw-express-cache/node_modules/isolated-vm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
make: Entering directory `/home/ec2-user/redstone-sw-express-cache/node_modules/isolated-vm/build'
  CXX(target) Release/obj.target/nortti/src/external_copy/serializer_nortti.o
  CXX(target) Release/obj.target/nortti/src/isolate/allocator_nortti.o
  AR(target) Release/obj.target/nortti.a
  COPY Release/nortti.a
  CXX(target) Release/obj.target/isolated_vm/src/external_copy/external_copy.o
  CXX(target) Release/obj.target/isolated_vm/src/external_copy/serializer.o
  CXX(target) Release/obj.target/isolated_vm/src/external_copy/string.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
../src/isolate/environment.cc:25:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE

<command-line>:0:0: note: this is the location of the previous definition
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [Release/obj.target/isolated_vm/src/external_copy/external_copy.o] Error 4
make: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [Release/obj.target/isolated_vm/src/isolate/environment.o] Error 4
make: Leaving directory `/home/ec2-user/redstone-sw-express-cache/node_modules/isolated-vm/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.10.82-83.359.amzn2.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v17.3.1/bin/node" "/home/ec2-user/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /home/ec2-user/redstone-sw-express-cache/node_modules/isolated-vm
gyp ERR! node -v v17.3.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
```

**Comment by ppedziwiatr** [comment]
Also - on the EC2 with `Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1020-aws x86_64)` - after `sudo apt-get install python g++ build-essential` - it makes the whole system to freeze...I had to make a hard restart after about an hour of waiting...

Unfortunately this makes this great library kinda unusable in a prod env...

It works fine though on my development machine (Apple M1)

**Comment by ppedziwiatr** [comment]
I've also tested it on my old development machine with Fedora 34.
After `sudo yum install gcc gcc-c++` I'm getting these errors:

```
AR(target) Release/obj.target/nortti.a
  COPY Release/nortti.a
  CXX(target) Release/obj.target/isolated_vm/src/external_copy/external_copy.o
  CXX(target) Release/obj.target/isolated_vm/src/external_copy/serializer.o
  CXX(target) Release/obj.target/isolated_vm/src/external_copy/string.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
../src/isolate/environment.cc:25: warning: "_GNU_SOURCE" redefined
   25 | #define _GNU_SOURCE
      |
<command-line>: note: this is the location of the previous definition
  CXX(target) Release/obj.target/isolated_vm/src/isolate/executor.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/holder.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/inspector.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/platform_delegate.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/scheduler.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/stack_trace.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/three_phase_task.o
  CXX(target) Release/obj.target/isolated_vm/src/lib/thread_pool.o
  CXX(target) Release/obj.target/isolated_vm/src/lib/timer.o
  CXX(target) Release/obj.target/isolated_vm/src/module/callback.o
  CXX(target) Release/obj.target/isolated_vm/src/module/context_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/evaluation.o
  CXX(target) Release/obj.target/isolated_vm/src/module/external_copy_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/isolate.o
  CXX(target) Release/obj.target/isolated_vm/src/module/isolate_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/lib_handle.o
../src/module/lib_handle.cc: In member function ‘v8::Local<v8::Value> ivm::LibHandle::PrivateSymbol(v8::MaybeLocal<v8::String>)’:
../src/module/lib_handle.cc:58:17: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   58 |         return *reinterpret_cast<Local<Value>*>(&symbol);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/module/lib_handle.cc:58:17: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX(target) Release/obj.target/isolated_vm/src/module/module_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/native_module_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/reference_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/script_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/session_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/module/transferable.o
  SOLINK_MODULE(target) Release/obj.target/isolated_vm.node
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -luv
/usr/bin/ld: cannot find -lbrotlidec
/usr/bin/ld: cannot find -lbrotlienc
/usr/bin/ld: cannot find -lnghttp2
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status
make: *** [[isolated_vm.target.mk:225](http://isolated_vm.target.mk:225/): Release/obj.target/isolated_vm.node] Błąd 1
make: Opuszczenie katalogu '/home/ppedziwiatr/Projects/isolated-test/node_modules/isolated-vm/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.11.19-300.fc34.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /home/ppedziwiatr/Projects/isolated-test/node_modules/isolated-vm
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by ppedziwiatr** [comment]
I've made another try on another a fresh Droplet on DigitialOcean on `Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)`

After installing gcc and trying to add `isolated-vm` as a dependency:
```
root@ubuntu-s-1vcpu-1gb-ams3-01-isolated-vm:~/isolated-vm# npm add isolated-vm
(##################) ⠼ reify:isolated-vm: sill audit bulk request { 'isolated-vm': [ '4.4.1' ] }
(##################) ⠼ reify:isolated-vm: sill audit bulk request { 'isolated-vm': [ '4.4.1' ] }
npm ERR! code 1
npm ERR! path /root/isolated-vm/node_modules/isolated-vm
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild --release -j 4
npm ERR! make: Entering directory '/root/isolated-vm/node_modules/isolated-vm/build'
npm ERR!   CXX(target) Release/obj.target/nortti/src/external_copy/serializer_nortti.o
npm ERR!   CXX(target) Release/obj.target/nortti/src/isolate/allocator_nortti.o
npm ERR!   AR(target) Release/obj.target/nortti.a
npm ERR!   COPY Release/nortti.a
npm ERR!   CXX(target) Release/obj.target/isolated_vm/src/external_copy/external_copy.o
npm ERR!   CXX(target) Release/obj.target/isolated_vm/src/external_copy/serializer.o
npm ERR!   CXX(target) Release/obj.target/isolated_vm/src/external_copy/string.o
npm ERR!   CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
npm ERR! make: Leaving directory '/root/isolated-vm/node_modules/isolated-vm/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.15.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/isolated-vm/node_modules/isolated-vm/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.15.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.15.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.15.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/isolated-vm/node_modules/isolated-vm',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
npm ERR! ../src/isolate/environment.cc:25: warning: "_GNU_SOURCE" redefined
npm ERR!    25 | #define _GNU_SOURCE
npm ERR!       | 
npm ERR! <command-line>: note: this is the location of the previous definition
npm ERR! g++: fatal error: Killed signal terminated program cc1plus
npm ERR! compilation terminated.
npm ERR! make: *** [isolated_vm.target.mk:191: Release/obj.target/isolated_vm/src/external_copy/external_copy.o] Error 1
npm ERR! make: *** Waiting for unfinished jobs....
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.4.0-107-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
npm ERR! gyp ERR! cwd /root/isolated-vm/node_modules/isolated-vm
npm ERR! gyp ERR! node -v v16.15.1
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-24T19_40_08_321Z-debug-0.log
```

**Comment by laverdet** [comment]
That looks like the oom reaper. Increase the memory of your container.

**Comment by ppedziwiatr** [comment]
Oh, that's unfortunate :/ we're using lots of t3.micro instances on AWS or basic droplets on DigitalOcean (that are running our node.js applications) and none of them required so far more than 0.5-1GB of memory..I believe it would useful to specify mem requirements in the docs..
Anyway, I'll test it with a droplet with 2GB of ram..

**Comment by ppedziwiatr** [comment]
Ok, I can confirm that it workd on DigitalOcean Droplet with these specs: `2 GB Memory / 50 GB Disk / AMS3 - Ubuntu 20.04 (LTS) x64`

**Comment by laverdet** [comment]
It sounds like you should be compiling on a stronger host and deploying to the smaller instances

**Comment by laverdet** [comment]
The runtime requirements are modest but compilation of any C++ project can be strenuous. I recommend deploying a minimal tarball to your worker hosts.

**Comment by ppedziwiatr** [comment]
Ok, we will need to investigate the possible options. Thanks for help!
I still had no success in installing this on Fedora 34, that's probably a matter of adding the missing libs via `dnf`
