### ISSUE TITLE
Missing packages for Docker.

### ISSUE THREAD

**Issue by Valanap** [laverdet/isolated-vm#404]
Which packages are needed? 
Having difficulties of deploying app to Docker using node 18 official image.

```
The command '/bin/sh -c npm ci' returned a non-zero code: 1
npm ERR!     /root/.npm/_logs/2023-09-13T23_47_32_178Z-debug-0.log
npm ERR! A complete log of this run can be found in:

npm ERR! gyp ERR! not ok
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! cwd /usr/src/app/node_modules/isolated-vm
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
npm ERR! gyp ERR! System Linux 5.10.0-24-cloud-amd64
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:432:5)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python 
npm ERR! gyp info using node@18.12.1 | linux | x64
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info it worked if it ends with ok
npm ERR! prebuild-install warn install /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/src/app/node_modules/isolated-vm/out/isolated_vm.node)
npm ERR! command sh -c -- prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
npm ERR! command failed
npm ERR! path /usr/src/app/node_modules/isolated-vm
npm ERR! code 1
```

Installing python didn help much and are getting different errors ```RUN apt-get update && apt-get install -y python3```.

**Comment by c121914yu** [comment]
How did you solve it?
