### ISSUE TITLE
Compile error with node v23.0.0

### ISSUE THREAD

**Issue by DPOH-VAR** [laverdet/isolated-vm#500]
## The Code
```
npm install
```
Error: `C++20 or later required.`

---
detailed logs:

windows 11 x64
```
npm error code 1
npm error path C:\PROJECTS\varhub-web-server\node_modules\isolated-vm
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
npm error cl : ��������� ��ப�  warning D9025: ��८�।������ "/std:c++20" �� "/std:c++17" [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\nortti.vcxproj]
npm error   serializer_nortti.cc
npm error cl : ��������� ��ப�  warning D9025: ��८�।������ "/GR-" �� "/GR" [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\nortti.vcxproj]
npm error cl : ��������� ��ப�  warning D9025: ��८�।������ "/std:c++20" �� "/std:c++17" [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\isolated_vm.vcxproj]
npm error   external_copy.cc
npm error cl : ��������� ��ப�  warning D9025: ��८�।������ "/GR-" �� "/GR" [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\isolated_vm.vcxproj]
npm error C:\Users\dpohvar\AppData\Local\node-gyp\Cache\23.0.0\include\node\v8config.h(13,1): fatal  error C1189: #error:  "C++20 or later required." [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\nortti.vcxproj]
npm error C:\Users\dpohvar\AppData\Local\node-gyp\Cache\23.0.0\include\node\v8config.h(13,1): fatal  error C1189: #error:  "C++20 or later required." [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\isolated_vm.vcxproj]
npm error prebuild-install warn install No prebuilt binaries found (target=23.0.0 runtime=node arch=x64 libc= platform=win32)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@23.0.0 | win32 | x64
npm error gyp info find Python using Python version 3.11.2 found at "C:\Users\dpohvar\AppData\Local\Programs\Python\Python311\python.exe"
npm error (node:2188) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
npm error (Use `node --trace-warnings ...` to show where the warning was created)
npm error gyp http GET https://nodejs.org/download/release/v23.0.0/node-v23.0.0-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v23.0.0/node-v23.0.0-headers.tar.gz
npm error gyp http GET https://nodejs.org/download/release/v23.0.0/SHASUMS256.txt
npm error gyp http GET https://nodejs.org/download/release/v23.0.0/win-x64/node.lib
npm error gyp http 200 https://nodejs.org/download/release/v23.0.0/SHASUMS256.txt
npm error gyp http 200 https://nodejs.org/download/release/v23.0.0/win-x64/node.lib
npm error gyp info find VS using VS2022 (17.5.33516.290) found at:
npm error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Users\dpohvar\AppData\Local\Programs\Python\Python311\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'C:\\SOFT\\nvm\\v23.0.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\PROJECTS\\varhub-web-server\\node_modules\\isolated-vm\\build\\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\SOFT\\nvm\\v23.0.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\dpohvar\\AppData\\Local\\node-gyp\\Cache\\23.0.0\\include\\node\\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\\Users\\dpohvar\\AppData\\Local\\node-gyp\\Cache\\23.0.0',
npm error gyp info spawn args '-Dnode_gyp_dir=C:\\SOFT\\nvm\\v23.0.0\\node_modules\\npm\\node_modules\\node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\dpohvar\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\23.0.0\\\\<(target_arch)\\\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=C:\\PROJECTS\\varhub-web-server\\node_modules\\isolated-vm',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'C:\\PROJECTS\\varhub-web-server\\node_modules\\isolated-vm\\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'build\\binding.sln',
npm error gyp info spawn args '/clp:Verbosity=minimal',
npm error gyp info spawn args '/nologo',
npm error gyp info spawn args '/p:Configuration=Release;Platform=x64',
npm error gyp info spawn args '/m:16'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (C:\SOFT\nvm\v23.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:216:23)
npm error gyp ERR! stack at ChildProcess.emit (node:events:507:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Windows_NT 10.0.27723
npm error gyp ERR! command "C:\\SOFT\\nodejs\\node.exe" "C:\\SOFT\\nvm\\v23.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release" "-j" "max"
npm error gyp ERR! cwd C:\PROJECTS\varhub-web-server\node_modules\isolated-vm
npm error gyp ERR! node -v v23.0.0
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: C:\Users\dpohvar\AppData\Local\npm-cache\_logs\2024-10-21T22_59_05_381Z-debug-0.log
```

docker:
```
FROM node:alpine3.20
RUN apk add --no-cache python3 py3-pip make build-base git
RUN npm install
```
```
 > [6/6] RUN npm install:
2.708 (node:1) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
2.708 (Use `node --trace-warnings ...` to show where the warning was created)
50.60 npm error code 1
50.60 npm error git dep preparation failed
50.60 npm error command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
50.60 npm error npm warn using --force Recommended protections disabled.
50.60 npm error (node:39) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
50.60 npm error (Use `node --trace-warnings ...` to show where the warning was created)
50.60 npm error npm error code 1
50.60 npm error npm error path /root/.npm/_cacache/tmp/git-clonePflONm/node_modules/isolated-vm
50.60 npm error npm error command failed
50.60 npm error npm error command sh -c prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
50.60 npm error npm error make: Entering directory '/root/.npm/_cacache/tmp/git-clonePflONm/node_modules/isolated-vm/build'
50.60 npm error npm error   CXX(target) Release/obj.target/nortti/src/external_copy/serializer_nortti.o
50.60 npm error npm error   CXX(target) Release/obj.target/nortti/src/isolate/allocator_nortti.o
50.60 npm error npm error make: Leaving directory '/root/.npm/_cacache/tmp/git-clonePflONm/node_modules/isolated-vm/build'
50.60 npm error npm error prebuild-install warn install No prebuilt binaries found (target=23.0.0 runtime=node arch=x64 libc=musl platform=linux)
50.60 npm error npm error gyp info it worked if it ends with ok
50.60 npm error npm error gyp info using node-gyp@10.2.0
50.60 npm error npm error gyp info using node@23.0.0 | linux | x64
50.60 npm error npm error gyp info find Python using Python version 3.12.7 found at "/usr/bin/python3"
50.60 npm error npm error (node:331) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time    
50.60 npm error npm error (Use `node --trace-warnings ...` to show where the warning was created)
50.60 npm error npm error gyp http GET https://unofficial-builds.nodejs.org/download/release/v23.0.0/node-v23.0.0-headers.tar.gz
50.60 npm error npm error gyp http 200 https://unofficial-builds.nodejs.org/download/release/v23.0.0/node-v23.0.0-headers.tar.gz
50.60 npm error npm error gyp http GET https://unofficial-builds.nodejs.org/download/release/v23.0.0/SHASUMS256.txt
50.60 npm error npm error gyp http 200 https://unofficial-builds.nodejs.org/download/release/v23.0.0/SHASUMS256.txt
50.60 npm error npm error gyp info spawn /usr/bin/python3
50.60 npm error npm error gyp info spawn args [
50.60 npm error npm error gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
50.60 npm error npm error gyp info spawn args 'binding.gyp',
50.60 npm error npm error gyp info spawn args '-f',
50.60 npm error npm error gyp info spawn args 'make',
50.60 npm error npm error gyp info spawn args '-I',
50.60 npm error npm error gyp info spawn args '/root/.npm/_cacache/tmp/git-clonePflONm/node_modules/isolated-vm/build/config.gypi',
50.60 npm error npm error gyp info spawn args '-I',
50.60 npm error npm error gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
50.60 npm error npm error gyp info spawn args '-I',
50.60 npm error npm error gyp info spawn args '/root/.cache/node-gyp/23.0.0/include/node/common.gypi',
50.60 npm error npm error gyp info spawn args '-Dlibrary=shared_library',
50.60 npm error npm error gyp info spawn args '-Dvisibility=default',
50.60 npm error npm error gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/23.0.0',
50.60 npm error npm error gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
50.60 npm error npm error gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/23.0.0/<(target_arch)/node.lib',
50.60 npm error npm error gyp info spawn args '-Dmodule_root_dir=/root/.npm/_cacache/tmp/git-clonePflONm/node_modules/isolated-vm',
50.60 npm error npm error gyp info spawn args '-Dnode_engine=v8',
50.60 npm error npm error gyp info spawn args '--depth=.',
50.60 npm error npm error gyp info spawn args '--no-parallel',
50.60 npm error npm error gyp info spawn args '--generator-output',
50.60 npm error npm error gyp info spawn args 'build',
50.60 npm error npm error gyp info spawn args '-Goutput_dir=.'
50.60 npm error npm error gyp info spawn args ]
50.60 npm error npm error gyp info spawn make
50.60 npm error npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 16 ]
50.60 npm error npm error In file included from /root/.cache/node-gyp/23.0.0/include/node/cppgc/common.h:8,
50.60 npm error npm error                  from /root/.cache/node-gyp/23.0.0/include/node/v8.h:23,
50.60 npm error npm error                  from ../src/external_copy/external_copy.h:2,
50.60 npm error npm error                  from ../src/external_copy/serializer.h:2,
50.60 npm error npm error                  from ../src/external_copy/serializer_nortti.cc:1:
50.60 npm error npm error /root/.cache/node-gyp/23.0.0/include/node/v8config.h:13:2: error: #error "C++20 or later required."
50.60 npm error npm error    13 | #error "C++20 or later required."
50.60 npm error npm error       |  ^~~~~
50.60 npm error npm error In file included from /root/.cache/node-gyp/23.0.0/include/node/cppgc/common.h:8,
50.60 npm error npm error                  from /root/.cache/node-gyp/23.0.0/include/node/v8.h:23,
50.60 npm error npm error                  from ../src/isolate/allocator.h:2,
50.60 npm error npm error                  from ../src/isolate/allocator_nortti.cc:1:
50.60 npm error npm error /root/.cache/node-gyp/23.0.0/include/node/v8config.h:13:2: error: #error "C++20 or later required."
50.60 npm error npm error    13 | #error "C++20 or later required."
50.60 npm error npm error       |  ^~~~~
50.60 npm error npm error In file included from ../src/external_copy/external_copy.h:12:
50.60 npm error npm error ../src/isolate/util.h:30:40: error: 'CopyablePersistentTraits' is not a member of 'v8'; did you mean 'NonCopyablePersistentTraits'?   
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error       |                                        NonCopyablePersistentTraits
50.60 npm error npm error ../src/isolate/util.h:30:65: error: template argument 2 is invalid
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                                                 ^
50.60 npm error npm error ../src/isolate/util.h:30:40: error: 'CopyablePersistentTraits' is not a member of 'v8'; did you mean 'NonCopyablePersistentTraits'?   
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error       |                                        NonCopyablePersistentTraits
50.60 npm error npm error ../src/isolate/util.h:30:66: error: template argument 2 is invalid
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                                                  ^~
50.60 npm error npm error ../src/isolate/util.h:30:40: error: 'CopyablePersistentTraits' is not a member of 'v8'; did you mean 'NonCopyablePersistentTraits'?   
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error       |                                        NonCopyablePersistentTraits
50.60 npm error npm error ../src/isolate/util.h:30:66: error: template argument 2 is invalid
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                                                  ^~
50.60 npm error npm error ../src/isolate/util.h:30:18: error: invalid template-id
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                  ^~
50.60 npm error npm error ../src/isolate/util.h:30:40: error: 'CopyablePersistentTraits' is not a member of 'v8'; did you mean 'NonCopyablePersistentTraits'?   
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error       |                                        NonCopyablePersistentTraits
50.60 npm error npm error ../src/isolate/util.h:30:66: error: 'template<class T> auto ivm::Deref' conflicts with a previous declaration
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                                                  ^~
50.60 npm error npm error ../src/isolate/util.h:25:6: note: previous declaration 'v8::Local<T> ivm::Deref(const v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&)'
50.60 npm error npm error    25 | auto Deref(const v8::Persistent<T>& handle) -> v8::Local<T> {
50.60 npm error npm error       |      ^~~~~
50.60 npm error npm error ../src/isolate/util.h:30:12: error: expected primary-expression before 'const'
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |            ^~~~~
50.60 npm error npm error ../src/isolate/util.h:30:77: error: expected ';' before '->' token
50.60 npm error npm error    30 | auto Deref(const v8::Persistent<T, v8::CopyablePersistentTraits<T>>& handle) -> v8::Local<T> {
50.60 npm error npm error       |                                                                             ^~~
50.60 npm error npm error       |                                                                             ;
50.60 npm error npm error In file included from ../src/isolate/holder.h:2,
50.60 npm error npm error                  from ../src/isolate/executor.h:6,
50.60 npm error npm error                  from ../src/isolate/environment.h:7,
50.60 npm error npm error                  from ../src/isolate/allocator_nortti.cc:2:
50.60 npm error npm error ../src/isolate/platform_delegate.h:15:22: error: 'void ivm::TaskRunner::PostTask(std::unique_ptr<v8::Task>)' marked 'override', but does not override
50.60 npm error npm error    15 |                 void PostTask(std::unique_ptr<v8::Task> task) override = 0;
50.60 npm error npm error       |                      ^~~~~~~~
50.60 npm error npm error ../src/isolate/platform_delegate.h:15:22: error: initializer specified for non-virtual method 'void ivm::TaskRunner::PostTask(std::unique_ptr<v8::Task>)'
50.60 npm error npm error ../src/isolate/platform_delegate.h:16:22: error: 'void ivm::TaskRunner::PostDelayedTask(std::unique_ptr<v8::Task>, double)' marked 'override', but does not override
50.60 npm error npm error    16 |                 void PostDelayedTask(std::unique_ptr<v8::Task> task, double delay_in_seconds) override = 0;
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/platform_delegate.h:16:22: error: initializer specified for non-virtual method 'void ivm::TaskRunner::PostDelayedTask(std::unique_ptr<v8::Task>, double)'
50.60 npm error npm error ../src/isolate/platform_delegate.h:17:22: error: 'void ivm::TaskRunner::PostIdleTask(std::unique_ptr<v8::IdleTask>)' marked 'final', but is not virtual
50.60 npm error npm error    17 |                 void PostIdleTask(std::unique_ptr<v8::IdleTask> /*task*/) final { std::terminate(); }
50.60 npm error npm error       |                      ^~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/platform_delegate.h:21:22: error: 'void ivm::TaskRunner::PostNonNestableDelayedTask(std::unique_ptr<v8::Task>, double)' marked 'final', but is not virtual
50.60 npm error npm error    21 |                 void PostNonNestableDelayedTask(std::unique_ptr<v8::Task> /*task*/, double /*delay_in_seconds*/) final { std::terminate(); }
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/holder.h:55:22: error: 'void ivm::IsolateTaskRunner::PostTask(std::unique_ptr<v8::Task>)' marked 'final', but is not virtual
50.60 npm error npm error    55 |                 void PostTask(std::unique_ptr<v8::Task> task) final;
50.60 npm error npm error       |                      ^~~~~~~~
50.60 npm error npm error ../src/isolate/holder.h:56:22: error: 'void ivm::IsolateTaskRunner::PostDelayedTask(std::unique_ptr<v8::Task>, double)' marked 'final', but is not virtual
50.60 npm error npm error    56 |                 void PostDelayedTask(std::unique_ptr<v8::Task> task, double delay_in_seconds) final;
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/holder.h:57:22: error: 'void ivm::IsolateTaskRunner::PostNonNestableTask(std::unique_ptr<v8::Task>)' marked 'final', but is not virtual
50.60 npm error npm error    57 |                 void PostNonNestableTask(std::unique_ptr<v8::Task> task) final { PostTask(std::move(task)); }
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~~~~~
50.60 npm error npm error In file included from ../src/isolate/holder.h:2,
50.60 npm error npm error                  from ../src/isolate/remote_handle.h:2,
50.60 npm error npm error                  from ../src/isolate/util.h:36:
50.60 npm error npm error ../src/isolate/platform_delegate.h:15:22: error: 'void ivm::TaskRunner::PostTask(std::unique_ptr<v8::Task>)' marked 'override', but does not override
50.60 npm error npm error    15 |                 void PostTask(std::unique_ptr<v8::Task> task) override = 0;
50.60 npm error npm error       |                      ^~~~~~~~
50.60 npm error npm error ../src/isolate/platform_delegate.h:15:22: error: initializer specified for non-virtual method 'void ivm::TaskRunner::PostTask(std::unique_ptr<v8::Task>)'
50.60 npm error npm error ../src/isolate/platform_delegate.h:16:22: error: 'void ivm::TaskRunner::PostDelayedTask(std::unique_ptr<v8::Task>, double)' marked 'override', but does not override
50.60 npm error npm error    16 |                 void PostDelayedTask(std::unique_ptr<v8::Task> task, double delay_in_seconds) override = 0;
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/platform_delegate.h:16:22: error: initializer specified for non-virtual method 'void ivm::TaskRunner::PostDelayedTask(std::unique_ptr<v8::Task>, double)'
50.60 npm error npm error ../src/isolate/platform_delegate.h:17:22: error: 'void ivm::TaskRunner::PostIdleTask(std::unique_ptr<v8::IdleTask>)' marked 'final', but is not virtual
50.60 npm error npm error    17 |                 void PostIdleTask(std::unique_ptr<v8::IdleTask> /*task*/) final { std::terminate(); }
50.60 npm error npm error       |                      ^~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/platform_delegate.h:21:22: error: 'void ivm::TaskRunner::PostNonNestableDelayedTask(std::unique_ptr<v8::Task>, double)' marked 'final', but is not virtual
50.60 npm error npm error    21 |                 void PostNonNestableDelayedTask(std::unique_ptr<v8::Task> /*task*/, double /*delay_in_seconds*/) final { std::terminate(); }
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/holder.h:55:22: error: 'void ivm::IsolateTaskRunner::PostTask(std::unique_ptr<v8::Task>)' marked 'final', but is not virtual
50.60 npm error npm error    55 |                 void PostTask(std::unique_ptr<v8::Task> task) final;
50.60 npm error npm error       |                      ^~~~~~~~
50.60 npm error npm error ../src/isolate/holder.h:56:22: error: 'void ivm::IsolateTaskRunner::PostDelayedTask(std::unique_ptr<v8::Task>, double)' marked 'final', but is not virtual
50.60 npm error npm error    56 |                 void PostDelayedTask(std::unique_ptr<v8::Task> task, double delay_in_seconds) final;
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/holder.h:57:22: error: 'void ivm::IsolateTaskRunner::PostNonNestableTask(std::unique_ptr<v8::Task>)' marked 'final', but is not virtual
50.60 npm error npm error    57 |                 void PostNonNestableTask(std::unique_ptr<v8::Task> task) final { PostTask(std::move(task)); }
50.60 npm error npm error       |                      ^~~~~~~~~~~~~~~~~~~
50.60 npm error npm error ../src/isolate/environment.h:111:60: error: 'CopyablePersistentTraits' is not a member of 'v8'; did you mean 'NonCopyablePersistentTraits'?
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error       |                                                            NonCopyablePersistentTraits
50.60 npm error npm error ../src/isolate/environment.h:111:89: error: template argument 2 is invalid
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                                                         ^~~~~~~
50.60 npm error npm error ../src/isolate/environment.h:111:96: error: template argument 1 is invalid
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                                                                ^~
50.60 npm error npm error ../src/isolate/environment.h:111:96: error: template argument 2 is invalid
50.60 npm error npm error ../src/isolate/environment.h:111:98: error: expected unqualified-id before '>' token
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                                                                  ^
50.60 npm error npm error In file included from ../src/external_copy/serializer.h:3:
50.60 npm error npm error ../src/isolate/environment.h:111:60: error: 'CopyablePersistentTraits' is not a member of 'v8'; did you mean 'NonCopyablePersistentTraits'?
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
50.60 npm error npm error       |                                                            NonCopyablePersistentTraits
50.60 npm error npm error ../src/isolate/environment.h:111:89: error: template argument 2 is invalid
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                                                         ^~~~~~~
50.60 npm error npm error ../src/isolate/environment.h:111:96: error: template argument 1 is invalid
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                                                                ^~
50.60 npm error npm error ../src/isolate/environment.h:111:96: error: template argument 2 is invalid
50.60 npm error npm error ../src/isolate/environment.h:111:98: error: expected unqualified-id before '>' token
50.60 npm error npm error   111 |                 std::deque<v8::Persistent<v8::Promise, v8::CopyablePersistentTraits<v8::Promise>>> unhandled_promise_rejections;
50.60 npm error npm error       |                                                                                                  ^
50.60 npm error npm error In file included from ../src/module/transferable.h:2,
50.60 npm error npm error                  from ../src/external_copy/serializer_nortti.cc:3:
50.60 npm error npm error ../src/isolate/class_handle.h: In member function 'void ivm::ClassHandle::TemplateDefinition::Add(const char*, ivm::detail::MemberAccessorHolder, Args ...)':
50.60 npm error npm error ../src/isolate/class_handle.h:95:40: error: 'class v8::ObjectTemplate' has no member named 'SetAccessor'
50.60 npm error npm error    95 |                                 proto->SetAccessor(name_handle, impl.getter.callback, impl.setter.callback);
50.60 npm error npm error       |                                        ^~~~~~~~~~~
50.60 npm error npm error make: *** [nortti.target.mk:161: Release/obj.target/nortti/src/isolate/allocator_nortti.o] Error 1
50.60 npm error npm error make: *** Waiting for unfinished jobs....
50.60 npm error npm error make: *** [nortti.target.mk:161: Release/obj.target/nortti/src/external_copy/serializer_nortti.o] Error 1
50.60 npm error npm error gyp ERR! build error
50.60 npm error npm error gyp ERR! stack Error: `make` failed with exit code: 2
50.60 npm error npm error gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
50.60 npm error npm error gyp ERR! System Linux 5.15.153.1-microsoft-standard-WSL2
50.60 npm error npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "max"
50.60 npm error npm error gyp ERR! cwd /root/.npm/_cacache/tmp/git-clonePflONm/node_modules/isolated-vm
50.60 npm error npm error gyp ERR! node -v v23.0.0
50.60 npm error npm error gyp ERR! node-gyp -v v10.2.0
50.60 npm error npm error gyp ERR! not ok
50.60 npm error npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-21T23_05_13_709Z-debug-0.log
50.61 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-21T23_05_06_082Z-debug-0.log
```

**Comment by laverdet** [comment]
We don't support odd-numbered releases of nodejs it is mentioned in the readme

**Comment by 0xdevalias** [comment]
> We don't support odd-numbered releases of nodejs it is mentioned in the readme

- https://github.com/laverdet/isolated-vm#security
  - > Additionally, it is wise to keep nodejs up to date through point releases which affect v8. You can find these on the [nodejs changelog](https://github.com/nodejs/node/blob/master/CHANGELOG.md) by looking for entries such as "update V8 to 9.1.269.36 (Michaël Zasso) \#38273". Historically there have usually been 3-5 of these updates within a single nodejs LTS release cycle. It is _not_ recommended to use odd-numbered nodejs releases since these frequently break ABI and API compatibility and isolated-vm doesn't aim to be compatible with bleeding edge v8.

@laverdet I understand there not being a pre-built binary based on that, which speaks to this part of the error:

```
npm error prebuild-install warn install No prebuilt binaries found (target=23.0.0 runtime=node arch=x64 libc= platform=win32)
```

But does that also explain this part?

```
npm error C:\Users\dpohvar\AppData\Local\node-gyp\Cache\23.0.0\include\node\v8config.h(13,1): fatal  error C1189: #error:  "C++20 or later required." [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\nortti.vcxproj]
npm error C:\Users\dpohvar\AppData\Local\node-gyp\Cache\23.0.0\include\node\v8config.h(13,1): fatal  error C1189: #error:  "C++20 or later required." [C:\PROJECTS\varhub-web-server\node_modules\isolated-vm\build\isolated_vm.vcxproj]
```

I don't begin to know the deeper specifics at play here, and whether C++20 is actually required, but I did see this commit mentioning C++17, which made me wonder:

- https://github.com/laverdet/isolated-vm/commit/d36adc23a5fb52a618e5147ee41c61f0f5560d6a

Though even if C++20 is required.. presumably that just means that for users to work around this error they just need to ensure they have the appropriate SDK/build tools for it installed in their windows environment, right?
