### ISSUE TITLE
Issue running on latest AWS Linux 2023 Instance

### ISSUE THREAD

**Issue by mikehuebner** [laverdet/isolated-vm#512]
## Is Your Question Already Answered?
- [x] I have read the [Frequently Asked Question](https://github.com/laverdet/isolated-vm?tab=readme-ov-file#frequently-asked-question) in the README. My question is not the Frequently Asked Question.

## Personal Diagnostics
Please answer the following questions:

#### JavaScript includes a `setTimeout` function:
- [x] Yes
- [ ] No

#### Functions are a type of primitive value in JavaScript:
- [ ] Yes
- [x] No

#### Objects can be shared between isolates:
- [ ] Yes
- [x] No
- [x] Also don't really work with isolates

## The Code
- [ ] This code will parse and evaluate if I put it into a file called `main.mjs` and then run `node main.mjs`.

```js
// Replace this code with the code which demonstrates what you are asking about
import ivm from "isolated-vm";
const isolate = new ivm.Isolate();
const context = await isolate.createContext();
console.log(await context.eval('"hello world"'));
```

Hey y'all, been trying to get `isolated-vm` `5.0.2` running with our Amazon Linux 2023 distro and keep coming across the same issue when we deploy to Elastic Beanstalk.

Error:
```
⨯ Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /var/app/current/node_modules/isolated-vm/out/isolated_vm.node)
   at Module._extensions..node (node:internal/modules/cjs/loader:1715:18)
   at Module.load (node:internal/modules/cjs/loader:1318:32)
   at Module._load (node:internal/modules/cjs/loader:1128:12)
   at TracingChannel.traceSync (node:diagnostics_channel:315:14)
   at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
   at Module.require (node:internal/modules/cjs/loader:1340:12)
   at mod.require (/var/app/current/node_modules/next/dist/server/require-hook.js:65:28)
   at Module.T (/var/app/current/dist/apps/public-app/.next/server/instrumentation.js:23:139328)
   at _require.i.require (/var/app/current/dist/apps/public-app/.next/server/instrumentation.js:23:140664)
   at require (node:internal/modules/helpers:141:16) {
 code: 'ERR_DLOPEN_FAILED'
}
```

## Details

Distro:
```
Node.js 22 running on 64bit Amazon Linux 2023/6.4.0
```

Packages:
- `isolated-vm` > `5.0.2`
- `builder.io/sdk` > `3.0.0`
- `nextjs` > `14.2.18`
- `nodejs` > `22.0.0`

Things I've tried:

1. Adding a `.ebextension` config to force install a newer version of gcc (`gcc-12`) -- fails due to not being able to be found
  - Tried doing `dnf` and `yum` for the installs, just reports back that the package cannot be found
  - Logged out the `GLIBCXX` versions and I get all the way to `3.4.29`, but not 30 😞 
3. Redeploy the distribution multiple times -- thought maybe with `5.0.2` and another issue reporting that they rebuild it using `gcc-11` that would fix it, but no difference
4. Try to rebuild the `isolated-vm` project with `gcc-11` instead of the default -- came across a ton of build errors just trying to get it compiled to the `out` directory. That is just my naivety with `node-gyp`, I kept getting syntax errors and that is why I just opened an issue as I didn't see another report of this with this linux distribution on AWS

Please let me know any details or other items I provide! ❤️

**Comment by mikehuebner** [comment]
@kaceycleveland seems to have figured out a workaround and its using the `.platform/hooks/prebuild` option with elastic beanstalk.

`.platform/hooks/prebuild`
```sh
apt-get update -y
apt-get install -y g++ libstdc++6
```

**Comment by laverdet** [comment]
Precompiled binaries in v5.0.3 should work on this platform now. I tested it personally via the amazonlinux:2023.6.20241010.0 docker image but let me know if it does not work.
