### ISSUE TITLE
Build requirements for 1.1.0+?

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#53]
I started getting build errors for our docker container, based on the official node.js image

Builds were fine for 1.0.2, but not 1.1.0.

Oddly, travis can build this fine, but not within our docker image. It's based off of node:8, which is based off of debian jessie: https://github.com/nodejs/docker-node/blob/4c7763dc2cb067becf12ea4bd55e88b881ccba2b/8/Dockerfile

Logs:
```
make: Entering directory '/usr/src/app/node_modules/isolated-vm/build'
  CXX(target) Release/obj.target/isolated_vm/src/isolate/allocator.o
In file included from ../src/isolate/allocator.cc:2:0:
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/isolated_vm/src/isolate/class_handle.o
In file included from ../src/isolate/remote_handle.h:3:0,
                 from ../src/isolate/util.h:6,
                 from ../src/isolate/convert_param.h:3,
                 from ../src/isolate/class_handle.h:4,
                 from ../src/isolate/class_handle.cc:1:
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
In file included from ../src/isolate/environment.cc:1:0:
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/isolated_vm/src/isolate/holder.o
In file included from ../src/isolate/holder.cc:2:0:
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:205:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
../src/isolate/holder.cc: In member function 'void ivm::IsolateHolder::Dispose()':
../src/isolate/holder.cc:14:102: error: no matching function for call to 'atomic_exchange(std::shared_ptr<ivm::IsolateEnvironment>*, std::shared_ptr<ivm::IsolateEnvironment>)'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
../src/isolate/holder.cc:14:102: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:914:5: note: template<class _ITp> _ITp std::atomic_exchange(std::atomic<_ITp>*, _ITp)
     atomic_exchange(atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:914:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:14:102: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:919:5: note: template<class _ITp> _ITp std::atomic_exchange(volatile std::atomic<_ITp>*, _ITp)
     atomic_exchange(volatile atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:919:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:14:102: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'volatile std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
../src/isolate/holder.cc: In member function 'std::shared_ptr<ivm::IsolateEnvironment> ivm::IsolateHolder::GetIsolate()':
../src/isolate/holder.cc:24:34: error: no matching function for call to 'atomic_load(std::shared_ptr<ivm::IsolateEnvironment>*)'
  return std::atomic_load(&isolate);
                                  ^
../src/isolate/holder.cc:24:34: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:904:5: note: template<class _ITp> _ITp std::atomic_load(const std::atomic<_ITp>*)
     atomic_load(const atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:904:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:24:34: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const std::atomic<_ITp>'
  return std::atomic_load(&isolate);
                                  ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:909:5: note: template<class _ITp> _ITp std::atomic_load(const volatile std::atomic<_ITp>*)
     atomic_load(const volatile atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:909:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:24:34: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const volatile std::atomic<_ITp>'
  return std::atomic_load(&isolate);
                                  ^
../src/isolate/holder.cc: In member function 'void ivm::IsolateHolder::ScheduleTask(std::unique_ptr<ivm::Runnable>, bool, bool)':
../src/isolate/holder.cc:28:64: error: no matching function for call to 'atomic_load(std::shared_ptr<ivm::IsolateEnvironment>*)'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
../src/isolate/holder.cc:28:64: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:904:5: note: template<class _ITp> _ITp std::atomic_load(const std::atomic<_ITp>*)
     atomic_load(const atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:904:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:28:64: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:909:5: note: template<class _ITp> _ITp std::atomic_load(const volatile std::atomic<_ITp>*)
     atomic_load(const volatile atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:909:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:28:64: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const volatile std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
../src/isolate/holder.cc: In member function 'std::shared_ptr<ivm::IsolateEnvironment> ivm::IsolateHolder::GetIsolate()':
../src/isolate/holder.cc:25:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
isolated_vm.target.mk:115: recipe for target 'Release/obj.target/isolated_vm/src/isolate/holder.o' failed
make: Leaving directory '/usr/src/app/node_modules/isolated-vm/build'
make: *** [Release/obj.target/isolated_vm/src/isolate/holder.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/src/app/node_modules/isolated-vm
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by laverdet** [comment]
That's strange because some of the lines it's complaining about, `v8::StartupData startup_data {}`, have been there since v0.0.x. Could you confirm which version of gcc you're using? At least version 5 is required. Or better yet, clang :)

**Comment by jeromegn** [comment]
gcc version should not have changed and 1.0.2 compiles fine (which also requires gcc 5+)

I just played with a lot of different options, including using clang (5.0.1 and 4.0). None of them worked right unfortunately. I tried gcc 6+ too, also failing. Different errors though!

Here's trying to build `v1.1.0` on different systems.

**g++ 6.3** (alpine linux 3.6)

```
> isolated-vm@1.1.0 install /usr/src/app/node_modules/isolated-vm
> node-gyp rebuild --release

make: Entering directory '/usr/src/app/node_modules/isolated-vm/build'
  CXX(target) Release/obj.target/isolated_vm/src/isolate/allocator.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/class_handle.o
In file included from ../src/isolate/class_handle.h:4:0,
                 from ../src/isolate/class_handle.cc:1:
../src/isolate/convert_param.h: In function 'std::__cxx11::string ivm::CalleeName(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/isolate/convert_param.h:15:128: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
  return std::string("`")+ *v8::String::Utf8Value(Unmaybe(info.Data()->ToString(v8::Isolate::GetCurrent()->GetCurrentContext())))+ "`";
                                                                                                                                ^
In file included from /root/.node-gyp/8.10.0/include/node/v8.h:26:0,
                 from ../src/isolate/class_handle.h:2,
                 from ../src/isolate/class_handle.cc:1:
/root/.node-gyp/8.10.0/include/node/v8.h:2776:32: note: declared here
                       explicit Utf8Value(Local<v8::Value> obj));
                                ^
/root/.node-gyp/8.10.0/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/isolate/class_handle.h:4:0,
                 from ../src/isolate/class_handle.cc:1:
../src/isolate/convert_param.h: In function 'std::__cxx11::string ivm::CalleeName(const v8::PropertyCallbackInfo<v8::Value>&)':
../src/isolate/convert_param.h:19:128: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
  return std::string("`")+ *v8::String::Utf8Value(Unmaybe(info.Data()->ToString(v8::Isolate::GetCurrent()->GetCurrentContext())))+ "`";
                                                                                                                                ^
In file included from /root/.node-gyp/8.10.0/include/node/v8.h:26:0,
                 from ../src/isolate/class_handle.h:2,
                 from ../src/isolate/class_handle.cc:1:
/root/.node-gyp/8.10.0/include/node/v8.h:2776:32: note: declared here
                       explicit Utf8Value(Local<v8::Value> obj));
                                ^
/root/.node-gyp/8.10.0/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/isolate/class_handle.h:4:0,
                 from ../src/isolate/class_handle.cc:1:
../src/isolate/convert_param.h: In function 'std::__cxx11::string ivm::CalleeName(const v8::PropertyCallbackInfo<void>&)':
../src/isolate/convert_param.h:23:128: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
  return std::string("`")+ *v8::String::Utf8Value(Unmaybe(info.Data()->ToString(v8::Isolate::GetCurrent()->GetCurrentContext())))+ "`";
                                                                                                                                ^
In file included from /root/.node-gyp/8.10.0/include/node/v8.h:26:0,
                 from ../src/isolate/class_handle.h:2,
                 from ../src/isolate/class_handle.cc:1:
/root/.node-gyp/8.10.0/include/node/v8.h:2776:32: note: declared here
                       explicit Utf8Value(Local<v8::Value> obj));
                                ^
/root/.node-gyp/8.10.0/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/isolate/class_handle.cc:1:0:
../src/isolate/class_handle.h: At global scope:
../src/isolate/class_handle.h:23:37: error: expected ')' before 'ptr'
    constexpr CtorFunction(nullptr_t ptr) : fn(ptr), args(0) {} // NOLINT
                                     ^~~
make: *** [isolated_vm.target.mk:115: Release/obj.target/isolated_vm/src/isolate/class_handle.o] Error 1
make: Leaving directory '/usr/src/app/node_modules/isolated-vm/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/src/app/node_modules/isolated-vm
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**clang 4.0.0** (alpine linux 3.6)

```
<snip>
In file included from ../src/isolate/class_handle.cc:1:
../src/isolate/class_handle.h:23:27: error: unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
                        constexpr CtorFunction(nullptr_t ptr) : fn(ptr), args(0) {} // NOLINT
                                               ^~~~~~~~~
                                               std::nullptr_t
/usr/bin/../lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../include/c++/6.3.0/x86_64-alpine-linux-musl/bits/c++config.h:205:29: note: 'std::nullptr_t' declared here
  typedef decltype(nullptr)     nullptr_t;
                                ^
3 warnings and 1 error generated.
make: *** [isolated_vm.target.mk:115: Release/obj.target/isolated_vm/src/isolate/class_handle.o] Error 1
```

(^ may not have been using clang I guess, I did set the proper environment variables though.)

**clang 3.5** (debian jessie)

```
<snip>
In file included from ../src/isolate/class_handle.cc:1:
../src/isolate/class_handle.h:23:27: error: unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
                        constexpr CtorFunction(nullptr_t ptr) : fn(ptr), args(0) {} // NOLINT
                                               ^~~~~~~~~
                                               std::nullptr_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:192:29: note: 'std::nullptr_t' declared here
  typedef decltype(nullptr)     nullptr_t;
                                ^
3 warnings and 1 error generated.
make: *** [Release/obj.target/isolated_vm/src/isolate/class_handle.o] Error 1
```

I'm sure I'm missing some package, but I'm not sure which one. Debian Jessie has the build essential stuff, and alpine had the build-base package (g++ and all.)

**Comment by jeromegn** [comment]
I just tried with the official node.js docker image and got this:

```
$ docker build .
Sending build context to Docker daemon  21.92MB
Step 1/5 : FROM node:8.10
 ---> 732a6fe5c376
Step 2/5 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> fb6d005b9f33
Step 3/5 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 650bcd4d609a
Step 4/5 : COPY . /usr/src/app
 ---> Using cache
 ---> c416cc12a34b
Step 5/5 : RUN npm install --unsafe-perm
 ---> Running in 26e8eac9b65b

> isolated-vm@1.3.0 install /usr/src/app
> node-gyp rebuild --release

make: Entering directory '/usr/src/app/build'
  CXX(target) Release/obj.target/isolated_vm/src/isolate/allocator.o
In file included from ../src/isolate/allocator.cc:2:0:
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/isolated_vm/src/isolate/class_handle.o
In file included from ../src/isolate/remote_handle.h:3:0,
                 from ../src/isolate/util.h:6,
                 from ../src/isolate/convert_param.h:3,
                 from ../src/isolate/class_handle.h:4,
                 from ../src/isolate/class_handle.cc:1:
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
In file included from ../src/isolate/environment.cc:1:0:
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/isolated_vm/src/isolate/holder.o
In file included from ../src/isolate/holder.cc:2:0:
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:302:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
../src/isolate/holder.cc: In member function 'void ivm::IsolateHolder::Dispose()':
../src/isolate/holder.cc:14:102: error: no matching function for call to 'atomic_exchange(std::shared_ptr<ivm::IsolateEnvironment>*, std::shared_ptr<ivm::IsolateEnvironment>)'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
../src/isolate/holder.cc:14:102: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:914:5: note: template<class _ITp> _ITp std::atomic_exchange(std::atomic<_ITp>*, _ITp)
     atomic_exchange(atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:914:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:14:102: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:919:5: note: template<class _ITp> _ITp std::atomic_exchange(volatile std::atomic<_ITp>*, _ITp)
     atomic_exchange(volatile atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:919:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:14:102: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'volatile std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
../src/isolate/holder.cc: In member function 'std::shared_ptr<ivm::IsolateEnvironment> ivm::IsolateHolder::GetIsolate()':
../src/isolate/holder.cc:24:34: error: no matching function for call to 'atomic_load(std::shared_ptr<ivm::IsolateEnvironment>*)'
  return std::atomic_load(&isolate);
                                  ^
../src/isolate/holder.cc:24:34: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:904:5: note: template<class _ITp> _ITp std::atomic_load(const std::atomic<_ITp>*)
     atomic_load(const atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:904:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:24:34: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const std::atomic<_ITp>'
  return std::atomic_load(&isolate);
                                  ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:909:5: note: template<class _ITp> _ITp std::atomic_load(const volatile std::atomic<_ITp>*)
     atomic_load(const volatile atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:909:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:24:34: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const volatile std::atomic<_ITp>'
  return std::atomic_load(&isolate);
                                  ^
../src/isolate/holder.cc: In member function 'void ivm::IsolateHolder::ScheduleTask(std::unique_ptr<ivm::Runnable>, bool, bool)':
../src/isolate/holder.cc:28:64: error: no matching function for call to 'atomic_load(std::shared_ptr<ivm::IsolateEnvironment>*)'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
../src/isolate/holder.cc:28:64: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:904:5: note: template<class _ITp> _ITp std::atomic_load(const std::atomic<_ITp>*)
     atomic_load(const atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:904:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:28:64: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:909:5: note: template<class _ITp> _ITp std::atomic_load(const volatile std::atomic<_ITp>*)
     atomic_load(const volatile atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:909:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:28:64: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const volatile std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
../src/isolate/holder.cc: In member function 'std::shared_ptr<ivm::IsolateEnvironment> ivm::IsolateHolder::GetIsolate()':
../src/isolate/holder.cc:25:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
isolated_vm.target.mk:115: recipe for target 'Release/obj.target/isolated_vm/src/isolate/holder.o' failed
make: Leaving directory '/usr/src/app/build'
make: *** [Release/obj.target/isolated_vm/src/isolate/holder.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/src/app
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@1.3.0 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-15T18_16_01_361Z-debug.log
The command '/bin/sh -c npm install --unsafe-perm' returned a non-zero code: 1
```

Here's the Dockerfile I used:

```dockerfile
FROM node:8.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm install --unsafe-perm
```

**Comment by laverdet** [comment]
It requires gcc 5 or higher. You are using 4.9:
> /usr/include/c++/**4.9**/atomic

You might also have a mismatched libstd++.

**Comment by jeromegn** [comment]
You're, this works now.

I can't figure out how it was working before. I looked at the docker images and they didn't change GCC version (we've been using 4.9 all along.) Odd.

Can you make a minor release for this?
