### ISSUE TITLE
New crash with latest 1.5.1

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#61]
I think this is new, here's 2 core dumps:

```
[Current thread is 1 (Thread 0x7fb07c846700 (LWP 38))]
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb0986b242a in __GI_abort () at abort.c:89
#2  0x00007fb0991e60ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fb0991e4066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fb0991e40b1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fb0991e42c9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fb09920cf3e in std::__throw_system_error(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fb09920f0e8 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fb096417b0c in thread_pool_t::resize (size=0, this=0x7fb096679640 <ivm::IsolateEnvironment::Scheduler::thread_pool>) at ../src/isolate/../thread_pool.h:130
#9  thread_pool_t::~thread_pool_t (this=0x7fb096679640 <ivm::IsolateEnvironment::Scheduler::thread_pool>, __in_chrg=<optimized out>) at ../src/isolate/../thread_pool.h:64
#10 0x00007fb0986b3940 in __run_exit_handlers (status=-1, listp=0x7fb098a175d8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
#11 0x00007fb0986b399a in __GI_exit (status=<optimized out>) at exit.c:105
#12 0x00007fb084368a7b in segfault_handler(int, siginfo_t*, void*) () from /usr/src/app/node_modules/segfault-handler/build/Release/segfault-handler.node
#13 <signal handler called>
#14 __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:286
#15 0x00005619306feb57 in v8::internal::JSTypedArray::MaterializeArrayBuffer(v8::internal::Handle<v8::internal::JSTypedArray>) ()
#16 0x00005619306fee80 in v8::internal::JSTypedArray::GetBuffer() ()
#17 0x00005619308ca73f in v8::internal::Runtime_TypedArrayGetBuffer(int, v8::internal::Object**, v8::internal::Isolate*) ()

... + around 120 lines of ??
```

and 

```
[Current thread is 1 (Thread 0x7fb82e99eb80 (LWP 13))]
(gdb) where
#0  0x00007fb82d559317 in kill () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000558c28bef669 in uv_kill (pid=<optimized out>, signum=<optimized out>) at ../deps/uv/src/unix/process.c:579
#2  0x0000558c289ab154 in node::Kill(v8::FunctionCallbackInfo<v8::Value> const&) ()
#3  0x0000558c281d92a8 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#4  0x0000558c282491ff in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) ()
#5  0x0000558c28249a89 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()

... + around 40 lines of ??
```

**Comment by laverdet** [comment]
See also ddopson/node-segfault-handler#49 for the cause of the second crash. What probably happened here is the first crash causes the crash in segfault-handler.
