### ISSUE TITLE
Node 10.6 (maybe earlier too) segfault

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#70]
Not sure if related to isolated-vm. Node 10.3 works with this code. This segfault happened using isolated-vm's latest master.

```
$ lldb node ./node_modules/.bin/mocha
(lldb) target create "node"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to 'node' (x86_64).
(lldb) settings set -- target.run-args  "./node_modules/.bin/mocha"
(lldb) r
Process 12129 launched: '/Users/jerome/.nvm/versions/node/v10.6.0/bin/node' (x86_64)


(node:12133) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  FileAppStore
    initialize
      ✓ throws error when bad working directory path is provided
      ✓ throws error if no code detected
      ✓ loads app with no config file
      ✓ loads app with config file
      ✓ interpolates secrets correctly
      ✓ picks config environment

  fly.http
new runtime, app: ./test/fixtures/apps/fly-http.js
Process 12129 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSEGV
    frame #0: 0x00007fff63ed34aa libsystem_kernel.dylib`__kill + 10
libsystem_kernel.dylib`__kill:
->  0x7fff63ed34aa <+10>: jae    0x7fff63ed34b4            ; <+20>
    0x7fff63ed34ac <+12>: movq   %rax, %rdi
    0x7fff63ed34af <+15>: jmp    0x7fff63ecab00            ; cerror_nocancel
    0x7fff63ed34b4 <+20>: retq
Target 0: (node) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSEGV
  * frame #0: 0x00007fff63ed34aa libsystem_kernel.dylib`__kill + 10
    frame #1: 0x000000010095ca75 node`uv_kill + 9
    frame #2: 0x0000000100038bf1 node`node::Kill(v8::FunctionCallbackInfo<v8::Value> const&) + 186
    frame #3: 0x000000010022b83f node`v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) + 623
    frame #4: 0x000000010022ad81 node`v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 689
    frame #5: 0x000000010022a3d0 node`v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 288
    frame #6: 0x00002a11279041bd
    frame #7: 0x00002a1127913a09
    frame #8: 0x00002a1127913a09
    frame #9: 0x00002a112790c5a3
    frame #10: 0x00002a1127913a09
    frame #11: 0x00002a112790c5a3
    frame #12: 0x00002a1127910f95
    frame #13: 0x00002a112790a4a1
    frame #14: 0x000000010051c207 node`v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, bool, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*, v8::internal::Handle<v8::internal::Object>, v8::internal::Execution::MessageHandling, v8::internal::Execution::Target) + 999
    frame #15: 0x000000010051bd86 node`v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 166
    frame #16: 0x00000001001bc78c node`v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 460
    frame #17: 0x0000000100032c5c node`node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) + 136
    frame #18: 0x0000000100032f02 node`node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) + 108
    frame #19: 0x000000010003b940 node`node::EmitExit(node::Environment*) + 285
    frame #20: 0x000000010003cdb9 node`node::Start(v8::Isolate*, node::IsolateData*, int, char const* const*, int, char const* const*) + 1375
    frame #21: 0x000000010003c55c node`node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) + 295
    frame #22: 0x000000010003c09e node`node::Start(int, char**) + 435
    frame #23: 0x0000000100001034 node`start + 52
```

**Comment by laverdet** [comment]
I don't see isolated-vm anywhere in that stack trace. Do you have any way I can reproduce it on my machine?

**Comment by jeromegn** [comment]
Sorry, my bad. I think this is something else.
