### ISSUE TITLE
Do you plan nodejs 11 support?

### ISSUE THREAD

**Issue by Exeteres** [laverdet/isolated-vm#84]
Nodejs v10.13.0 works fine, but on the latest version v11.1.0 I get the following build error. How soon will the latest version be supported?

```shell
yarn add v1.12.3
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/exeteres/Tests/node_modules/isolated-vm: Command failed.
Exit code: 1
Command: node-gyp rebuild --release -j 4
Arguments: 
Directory: /home/exeteres/Tests/node_modules/isolated-vm
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.1.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/exeteres/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/exeteres/Tests/node_modules/isolated-vm/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/exeteres/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/exeteres/.node-gyp/11.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/exeteres/.node-gyp/11.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/exeteres/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/exeteres/.node-gyp/11.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/exeteres/Tests/node_modules/isolated-vm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
make: вход в каталог «/home/exeteres/Tests/node_modules/isolated-vm/build»
  CXX(target) Release/obj.target/nortti/src/external_copy_nortti.o
  AR(target) Release/obj.target/nortti.a
  COPY Release/nortti.a
  CXX(target) Release/obj.target/isolated_vm/src/isolate/allocator.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/holder.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/class_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
In file included from ../src/isolate/environment.cc:3:0:
../src/isolate/inspector.h:3:10: fatal error: v8-inspector.h: Нет такого файла или каталога
 #include <v8-inspector.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
isolated_vm.target.mk:125: recipe for target 'Release/obj.target/isolated_vm/src/isolate/environment.o' failed
make: *** [Release/obj.target/isolated_vm/src/isolate/environment.o] Error 1
make: *** Ожидание завершения заданий…
make: выход из каталога «/home/exeteres/Tests/node_modules/isolated-vm/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/exeteres/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/home/exeteres/.nvm/versions/node/v11.1.0/bin/node" "/home/exeteres/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /home/exeteres/Tests/node_modules/isolated-vm
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by laverdet** [comment]
Odd-numbered versions of nodejs update the v8 version frequently so I focus on stable even-numbered versions. That is to say, I'll definitely be supporting nodejs v12.x. The nodejs team could do a better job of making this clear but odd-numbered versions are best for core and module developers.

**Comment by laverdet** [comment]
Support for v11.2.0 is on npm now. nodejs is allowed to break ABI compatibility on odd-numbered versions at any time though so please keep that in mind.
